import React from 'react';
import { StudioShell } from './components/StudioShell';
import type { FieldDef } from './components/StudioShell';

interface Props { onBack: () => void }

const fields: FieldDef[] = [
  { key: 'brandName',    label: 'Brand Name', type: 'text', placeholder: 'e.g. Meridian, Vault, Kova' },
  { key: 'industry',     label: 'Industry', type: 'text', placeholder: 'e.g. fintech, fashion, wellness' },
  { key: 'personality',  label: 'Brand Personality', type: 'select', options: ['Bold', 'Minimal', 'Luxury', 'Corporate', 'Approachable'] },
  { key: 'colorDir',     label: 'Color Direction', type: 'text', placeholder: 'e.g. deep navy and gold, muted earth tones' },
  { key: 'logoStyle',    label: 'Logo Style', type: 'select', options: ['Wordmark', 'Icon', 'Lettermark', 'Abstract', 'Combination'] },
];

const buildPrompt = (v: Record<string, string>) =>
  `Brand identity board for ${v.brandName || 'a modern brand'}, ` +
  `${v.industry ? v.industry + ' industry, ' : ''}` +
  `${v.logoStyle || 'wordmark'} logo concept, ` +
  `${v.personality || 'minimal'} aesthetic, ` +
  `${v.colorDir ? v.colorDir + ' palette, ' : ''}` +
  `professional brand presentation quality, clean white backdrop, ` +
  `brand guideline deck style, typographic hierarchy, ` +
  `no UI chrome, commercial identity presentation, real brand board layout`;

const assetTitle = (v: Record<string, string>) =>
  `${v.brandName || 'Brand'} — ${v.logoStyle || 'Wordmark'} · ${v.personality || 'Minimal'}`;

const implementationPlan = (v: Record<string, string>) => `${v.brandName || 'Brand'} — Identity Guidelines
Generated by: Brand Studio

Identity Overview
- Brand: ${v.brandName || 'Not specified'}
- Industry: ${v.industry || 'Not specified'}
- Personality: ${v.personality || 'Minimal'}
- Logo Style: ${v.logoStyle || 'Wordmark'}
- Color Direction: ${v.colorDir || 'To be defined'}

Logo Usage
- Primary: Full color on white/light backgrounds
- Reversed: White version on dark backgrounds
- Minimum size: 120px wide (digital), 1 inch (print)
- Clear space: Equal to cap-height on all sides

Color System
Primary: ${v.colorDir ? v.colorDir.split(' ')[0] : '[Define hex]'}
Secondary: [Complement to primary]
Neutral: #F5F5F5 (light), #1A1A1A (dark)
Accent: [Highlight color]

Typography
- Heading: [Sans-serif — suggest Inter, Neue Haas, or Söhne]
- Body: [System-ui or matched serif]
- Weight usage: 700 headlines, 400 body, 600 CTA

Tone of Voice
${v.personality === 'Luxury' ? '- Refined, exclusive, deliberate\n- No exclamation marks\n- Short, precise statements' :
  v.personality === 'Bold' ? '- Direct, confident, declarative\n- Active voice\n- Power words' :
  v.personality === 'Approachable' ? '- Warm, human, conversational\n- Second-person (you)\n- Avoid jargon' :
  '- Clear, professional, measured\n- Evidence-driven\n- Formal but not cold'}

Deliverables Checklist
[ ] Logo suite (SVG + PNG in all variants)
[ ] Color palette (hex, RGB, CMYK, Pantone)
[ ] Typography specimen sheet
[ ] Brand usage do/don't guide
[ ] Social media template set`;

export function BrandStudio({ onBack }: Props) {
  return (
    <StudioShell
      title="Brand Studio"
      description="Logo concepts, color palettes, typography systems, and brand identity boards. Built for real presentation use."
      onBack={onBack}
      fields={fields}
      buildPrompt={buildPrompt}
      assetTitle={assetTitle}
      implementationPlan={implementationPlan}
    />
  );
}
