import React from 'react';
import { StudioShell } from './components/StudioShell';
import type { FieldDef } from './components/StudioShell';

interface Props { onBack: () => void }

const fields: FieldDef[] = [
  { key: 'category',   label: 'Category', type: 'select', options: ['Outfit', 'Collection', 'Apparel Brand', 'Streetwear', 'Activewear'] },
  { key: 'direction',  label: 'Style Direction', type: 'select', options: ['Minimal', 'Streetwear', 'Luxury', 'Athletic', 'Editorial'] },
  { key: 'color',      label: 'Primary Color', type: 'text', placeholder: 'e.g. all-black, neutral earth, cobalt and white' },
  { key: 'market',     label: 'Target Market', type: 'text', placeholder: 'e.g. 18-30 urban males, women in fitness, luxury buyers' },
  { key: 'context',    label: 'Context or Season', type: 'text', placeholder: 'e.g. summer drop, AW24 collection, launch campaign' },
];

const buildPrompt = (v: Record<string, string>) =>
  `Fashion editorial visualization, ${v.category || 'outfit'} concept, ` +
  `${v.direction || 'minimal'} aesthetic, ` +
  `${v.color ? v.color + ' colorway, ' : ''}` +
  `${v.market ? 'targeting ' + v.market + ', ' : ''}` +
  `${v.context ? v.context + ' context, ' : ''}` +
  `professional lookbook quality, clean studio backdrop, ` +
  `fashion photography style, editorial lighting, no text overlays, ` +
  `commercial-ready visual, sharp garment detail, realistic fabric texture`;

const assetTitle = (v: Record<string, string>) =>
  `${v.category || 'Collection'} — ${v.direction || 'Minimal'} · ${v.context || 'Drop'}`;

const implementationPlan = (v: Record<string, string>) => `${v.category || 'Collection'} — Production Direction
Generated by: Fashion Studio

Collection Overview
- Category: ${v.category || 'Not specified'}
- Direction: ${v.direction || 'Minimal'}
- Color: ${v.color || 'Not specified'}
- Target Market: ${v.market || 'Not specified'}
- Context: ${v.context || 'Not specified'}

Fabric Direction
${v.direction === 'Luxury' ? '- Materials: Cashmere, silk, fine wool, leather accents\n- Finish: Clean seams, lined, structured\n- Production: Small-batch, quality-first' :
  v.direction === 'Streetwear' ? '- Materials: Heavyweight cotton, fleece, denim, nylon\n- Finish: Garment-washed, distressed options\n- Production: Print-on-demand or batch runs' :
  v.direction === 'Athletic' ? '- Materials: Moisture-wicking polyester, spandex, mesh panels\n- Finish: Flatlock seams, ergonomic cuts\n- Production: Technical sportswear manufacturer' :
  '- Materials: Cotton, linen, or sustainable alternatives\n- Finish: Clean, minimal construction\n- Production: Ethical small-batch or DTC model'}

Sizing Range
- Start: XS–XL (core launch)
- Extend: 2XL–3XL (based on demand)
- Fit model: ${v.market?.includes('women') ? 'Size 8 / M women\'s' : 'Size M men\'s'}

Collection Naming
- Line name: [Define — reference ${v.context || 'collection theme'}]
- SKU prefix: [3-letter brand code + season code]
- Colorway codes: [e.g., BLK-01, NTR-02]

Launch Channels
- Primary: Instagram, TikTok (lookbook content)
- Secondary: Brand website (Shopify recommended)
- Wholesale: Consignment or direct approach

Next Steps
1. Finalize sketches from generated visual direction
2. Source fabric swatches
3. Create tech packs per garment
4. Produce sample set (1-2 pieces per style)
5. Shoot lookbook using generated visual as reference
6. Launch pre-order or limited drop`;

export function FashionStudio({ onBack }: Props) {
  return (
    <StudioShell
      title="Fashion Studio"
      description="Outfit concepts, apparel collections, lookbook visuals, and editorial direction. Professional fashion presentation."
      onBack={onBack}
      fields={fields}
      buildPrompt={buildPrompt}
      assetTitle={assetTitle}
      implementationPlan={implementationPlan}
    />
  );
}
