import React from 'react';
import { StudioShell } from './components/StudioShell';
import type { FieldDef } from './components/StudioShell';

interface Props { onBack: () => void }

const fields: FieldDef[] = [
  { key: 'contentType', label: 'Content Type', type: 'select', options: ['Ad Creative', 'Instagram Post', 'Campaign Poster', 'Promo Graphic'] },
  { key: 'brandName',   label: 'Brand Name', type: 'text', placeholder: 'e.g. Apex Wear, Nova Finance' },
  { key: 'theme',       label: 'Campaign Theme', type: 'text', placeholder: 'e.g. Summer launch, Black Friday, Rebrand' },
  { key: 'offer',       label: 'Offer or Message', type: 'text', placeholder: 'e.g. 50% off, Free trial, New collection' },
  { key: 'cta',         label: 'Call-to-Action', type: 'text', placeholder: 'e.g. Shop Now, Start Free, Learn More' },
  { key: 'visualTone',  label: 'Visual Tone', type: 'select', options: ['Bold', 'Minimal', 'Corporate', 'Energetic', 'Luxury'] },
];

const buildPrompt = (v: Record<string, string>) =>
  `Professional ${v.contentType || 'ad creative'} design, ` +
  `${v.brandName ? 'brand: ' + v.brandName + ', ' : ''}` +
  `${v.theme ? v.theme + ' campaign, ' : ''}` +
  `${v.offer ? 'message: ' + v.offer + ', ' : ''}` +
  `${v.cta ? 'CTA: ' + v.cta + ', ' : ''}` +
  `${v.visualTone || 'bold'} visual tone, agency-level creative, ` +
  `clean composition, modern typography, commercial-ready design, ` +
  `high impact visuals, no UI chrome, print-quality output`;

const assetTitle = (v: Record<string, string>) =>
  `${v.brandName || 'Campaign'} — ${v.contentType || 'Creative'} · ${v.visualTone || 'Bold'}`;

const implementationPlan = (v: Record<string, string>) => `${v.brandName || 'Campaign'} — Marketing Plan
Generated by: Marketing Studio

Campaign Brief
- Type: ${v.contentType || 'Ad Creative'}
- Theme: ${v.theme || 'Not specified'}
- Message: ${v.offer || 'Not specified'}
- CTA: ${v.cta || 'Not specified'}
- Tone: ${v.visualTone || 'Bold'}

Distribution Channels
- Primary: ${(v.contentType || '').includes('Instagram') ? 'Instagram Feed + Stories' : 'Paid Social (Meta, Google)'}
- Secondary: Email header, Website banner

Copy Framework
- Headline: [Short punchy line referencing ${v.offer || 'the offer'}]
- Sub-copy: [Benefit statement — 1 sentence]
- CTA: ${v.cta || 'Click to learn more'}

A/B Test Recommendation
- Version A: ${v.visualTone || 'Bold'} visual with direct CTA
- Version B: Testimonial or social proof variant

Timeline
- Creative: 1-2 days
- Review: 1 day
- Launch: Day 3
- Performance review: Day 7, Day 14

Production Notes
Use generated asset as base reference.
Resize for: 1:1 (social), 9:16 (stories), 16:9 (banner).`;

export function MarketingStudio({ onBack }: Props) {
  return (
    <StudioShell
      title="Marketing Studio"
      description="Ad creatives, social content, campaign posters, and promo graphics at commercial production quality."
      onBack={onBack}
      fields={fields}
      buildPrompt={buildPrompt}
      assetTitle={assetTitle}
      implementationPlan={implementationPlan}
    />
  );
}
