import React from 'react';
import { StudioShell } from './components/StudioShell';
import type { FieldDef } from './components/StudioShell';

interface Props { onBack: () => void }

const fields: FieldDef[] = [
  { key: 'productType', label: 'Product Type', type: 'select', options: ['Packaging', 'Physical Product', 'Merchandise', 'Label', 'Box Design'] },
  { key: 'productName', label: 'Product Name', type: 'text', placeholder: 'e.g. Ember Candle Co., Vault Protein, Kova Watch' },
  { key: 'material',    label: 'Material / Finish', type: 'select', options: ['Matte', 'Glossy', 'Kraft', 'Frosted Glass', 'Metal', 'Fabric'] },
  { key: 'colorScheme', label: 'Color Scheme', type: 'text', placeholder: 'e.g. black and gold, white and sage, earth tones' },
  { key: 'style',       label: 'Visual Style', type: 'select', options: ['Minimal', 'Premium', 'Bold', 'Natural', 'Industrial'] },
];

const buildPrompt = (v: Record<string, string>) =>
  `High-realism ${v.productType || 'packaging'} mockup for ${v.productName || 'a premium product'}, ` +
  `${v.material || 'matte'} finish, ` +
  `${v.colorScheme ? v.colorScheme + ' color scheme, ' : ''}` +
  `${v.style || 'minimal'} design aesthetic, ` +
  `studio product photography style, clean white background, ` +
  `commercial presentation quality, sharp detail, professional product render, ` +
  `no text or labels visible, realistic lighting and shadows`;

const assetTitle = (v: Record<string, string>) =>
  `${v.productName || 'Product'} — ${v.productType || 'Packaging'} · ${v.style || 'Minimal'}`;

const implementationPlan = (v: Record<string, string>) => `${v.productName || 'Product'} — Production Specification
Generated by: Product Studio

Product Brief
- Type: ${v.productType || 'Packaging'}
- Name: ${v.productName || 'Not specified'}
- Material: ${v.material || 'Not specified'}
- Color Scheme: ${v.colorScheme || 'Not specified'}
- Visual Style: ${v.style || 'Minimal'}

Print / Production Specs
- Format: ${v.productType === 'Label' ? 'Die-cut label, vector file required' : 'Full structural dieline'}
- File format: Adobe Illustrator (AI) or PDF/X-1a
- Color mode: CMYK (print), RGB (digital preview)
- Bleed: 3mm all sides (print production)
- Resolution: 300dpi minimum for print assets

Material Direction
${v.material === 'Kraft' ? '- Uncoated kraft stock, natural tone\n- Ink: 1-2 spot colors recommended\n- Eco-positioning potential' :
  v.material === 'Metal' ? '- Aluminum or steel substrate\n- Anodized or powder-coated finish\n- Laser engraving or screen print' :
  v.material === 'Glossy' ? '- Coated gloss stock\n- Full-color digital or offset print\n- Consider UV spot coating for premium effect' :
  '- Standard coated stock\n- Offset or digital print\n- Review GSM based on product weight'}

Supplier Recommendation
- Packaging: Packlane, Arka, or The Packaging Company
- Labels: Sticker Mule, Avery, or local print shop
- Lead time: 7-14 business days typical

Next Steps
1. Finalize design file in Illustrator
2. Request printer dieline template
3. Order sample run (25-50 units)
4. Approve sample before full production
5. Scale order based on launch volume`;

export function ProductStudio({ onBack }: Props) {
  return (
    <StudioShell
      title="Product Studio"
      description="Packaging mockups, physical product renders, merchandise visuals, and label concepts. Commercial quality."
      onBack={onBack}
      fields={fields}
      buildPrompt={buildPrompt}
      assetTitle={assetTitle}
      implementationPlan={implementationPlan}
    />
  );
}
