import React from 'react';
import { StudioShell } from './components/StudioShell';
import type { FieldDef } from './components/StudioShell';

interface Props { onBack: () => void }

const fields: FieldDef[] = [
  { key: 'productType', label: 'Product Type', type: 'select', options: ['SaaS', 'Marketplace', 'Dashboard', 'Landing Page'] },
  { key: 'audience',    label: 'Target Audience', type: 'text', placeholder: 'e.g. startup founders, HR teams' },
  { key: 'tone',        label: 'Tone', type: 'select', options: ['Minimal', 'Corporate', 'Bold', 'Dark', 'Light'] },
  { key: 'color',       label: 'Primary Color', type: 'text', placeholder: 'e.g. deep blue, charcoal, sage green' },
  { key: 'feature',     label: 'Feature Focus', type: 'text', placeholder: 'e.g. analytics, onboarding, payments' },
  { key: 'platform',    label: 'Platform', type: 'select', options: ['Web', 'Mobile', 'Desktop'] },
];

const buildPrompt = (v: Record<string, string>) =>
  `High-fidelity ${v.productType || 'SaaS'} interface mockup, ` +
  `${v.tone || 'minimal'} design aesthetic, ` +
  `${v.platform || 'web'} screen proportions, ` +
  `${v.color || 'modern'} accent color, ` +
  `${v.feature ? v.feature + ' focused, ' : ''}` +
  `${v.audience ? 'targeting ' + v.audience + ', ' : ''}` +
  `grid-aligned UI layout, realistic interface components, product-ready design, ` +
  `no text labels, modern SaaS aesthetic, clean white space, professional quality`;

const assetTitle = (v: Record<string, string>) =>
  `${v.productType || 'App'} — ${v.tone || 'Minimal'} · ${v.platform || 'Web'}`;

const implementationPlan = (v: Record<string, string>) => `${v.productType || 'App'} — Implementation Plan
Generated by: Web & App Studio

Stack
- Frontend: React + TypeScript
- Styling: Tailwind CSS
- Platform: ${v.platform || 'Web'}
- Deployment: Vercel or Netlify

Folder Structure
/src
  /components
  /pages
  /hooks
  /styles
  /utils

Key Components
- Navigation / Sidebar
- ${v.feature ? v.feature.charAt(0).toUpperCase() + v.feature.slice(1) + ' module' : 'Core feature panel'}
- Authentication flow
- Dashboard layout

Dependencies
- react, react-router-dom
- tailwindcss
- ${v.feature?.toLowerCase().includes('analytics') ? 'recharts or chart.js' : 'headlessui/react'}
- lucide-react (icons)

Design Direction
- Tone: ${v.tone || 'Minimal'}
- Primary Color: ${v.color || 'to be defined'}
- Typography: Inter or system-ui, 400/600/700 weights
- Spacing: 4px base grid

Deployment Steps
1. npx create-react-app or Vite scaffold
2. Install Tailwind CSS
3. Build core layout components
4. Connect to backend API or mock data
5. Deploy to Vercel with CI/CD`;

export function WebAppStudio({ onBack }: Props) {
  return (
    <StudioShell
      title="Web & App Studio"
      description="High-fidelity UI mockups — SaaS dashboards, landing pages, mobile screens. Product-ready design direction."
      onBack={onBack}
      fields={fields}
      buildPrompt={buildPrompt}
      assetTitle={assetTitle}
      implementationPlan={implementationPlan}
    />
  );
}
