// ── engineering/types.ts — Engineering mission data types ────────────────────

export type MissionIntent = 'build' | 'fix' | 'refactor' | 'audit' | 'test' | 'docs';

export interface MissionStep {
  id: string;
  title: string;
  rationale: string;
  filesLikelyTouched: string[];
  risk: 'low' | 'med' | 'high';
  rollback: string;
  checks: string[];
}

export interface MissionPlan {
  missionId: string;
  requestId: string;
  goal: string;
  intent: MissionIntent;
  constraints: {
    noUiChanges: boolean;
    requireApproval: boolean;
    safePreviewOnly: boolean;
  };
  steps: MissionStep[];
}

/** Preview bundle for a single step — shown to user before applying. */
export interface PatchBundle {
  stepId: string;
  /** Unified diff string (preview only — never auto-applied) */
  diff: string;
  /** Files that will be touched */
  fileList: string[];
  rationale: string;
  safeToApply: boolean;
}

/** Full lifecycle state machine for a mission. */
export type MissionState =
  | 'idle'
  | 'planning'
  | 'patching'
  | 'preview_ready'
  | 'awaiting_approval'
  | 'executing'
  | 'applying'
  | 'verifying'
  | 'complete'
  | 'completed'
  | 'failed'
  | 'rolled_back';

// Legacy alias for backward compatibility with existing ipc.ts usage
export type MissionStatus = MissionState;

export interface MissionEvent {
  missionId: string;
  status: MissionState;
  plan?: MissionPlan;
  error?: string;
  stepId?: string;
}

/** A single candidate approach generated by the AI council. */
export interface CandidatePlan {
  id:    string;
  title: string;
  steps: MissionStep[];
  /** Score assigned by ExperimentEngine (0–100). Set after experiments run. */
  score?: number;
}

export interface MissionAuditEvent {
  type:
    | 'MISSION_START'
    | 'MISSION_PLAN'
    | 'MISSION_STEP_PREVIEW'
    | 'MISSION_STEP_APPLY'
    | 'MISSION_VERIFY'
    | 'MISSION_COMPLETE'
    | 'MISSION_FAILED'
    | 'MISSION_ROLLBACK';
  missionId: string;
  payload?: unknown;
  ts: number;
}
