// ── ventureCatalog.ts — 10 venture categories with operational metadata ──────
//
// Each category defines cost ranges, time to launch/revenue, automation fit,
// recommended site type, capture method, traffic channels, monetization paths,
// and whether the venture can operate before formal legal filing.

import type { VentureCategoryConfig } from './ventureTypes';

export const VENTURE_CATALOG: readonly VentureCategoryConfig[] = [
  {
    category: 'digital_product',
    label: 'Digital Product',
    description: 'E-books, templates, courses, printables, or digital toolkits sold online.',
    startupCostRange: [50, 300],
    timeToLaunch: '1-2 weeks',
    timeToFirstRevenue: '2-4 weeks',
    automationSuitability: 85,
    dailyPromoSuitability: 75,
    contentVelocity: 'medium',
    riskLevel: 'low',
    recommendedSiteType: 'landing_page',
    recommendedCaptureMethod: 'free_guide',
    trafficChannels: ['SEO articles', 'X/Twitter', 'Pinterest', 'YouTube Shorts', 'Reddit'],
    monetizationPaths: ['Direct sales', 'Upsell bundles', 'Email funnel'],
    canOperateBeforeFiling: true,
  },
  {
    category: 'content_brand',
    label: 'Content Brand',
    description: 'Authority-driven brand that publishes content across platforms, building audience first and monetizing through sponsorships, affiliates, or products.',
    startupCostRange: [0, 200],
    timeToLaunch: '3-7 days',
    timeToFirstRevenue: '4-8 weeks',
    automationSuitability: 90,
    dailyPromoSuitability: 95,
    contentVelocity: 'high',
    riskLevel: 'low',
    recommendedSiteType: 'content_hub',
    recommendedCaptureMethod: 'email_signup',
    trafficChannels: ['YouTube Shorts', 'TikTok', 'X/Twitter', 'SEO blog', 'Instagram Reels'],
    monetizationPaths: ['Sponsorships', 'Affiliate links', 'Digital products', 'Ad revenue'],
    canOperateBeforeFiling: true,
  },
  {
    category: 'newsletter',
    label: 'Newsletter',
    description: 'Curated or original email newsletter that grows a subscriber base and monetizes through sponsorships, paid tiers, or product recommendations.',
    startupCostRange: [0, 100],
    timeToLaunch: '1-3 days',
    timeToFirstRevenue: '4-8 weeks',
    automationSuitability: 90,
    dailyPromoSuitability: 80,
    contentVelocity: 'medium',
    riskLevel: 'low',
    recommendedSiteType: 'landing_page',
    recommendedCaptureMethod: 'email_signup',
    trafficChannels: ['X/Twitter', 'LinkedIn', 'Reddit', 'SEO', 'Cross-promotions'],
    monetizationPaths: ['Sponsorships', 'Paid subscriptions', 'Affiliate', 'Product launches'],
    canOperateBeforeFiling: true,
  },
  {
    category: 'faceless_media',
    label: 'Faceless Media',
    description: 'YouTube channels, social media accounts, or blogs run without personal identity — AI-scripted, stock-based, or screen-capture content.',
    startupCostRange: [50, 250],
    timeToLaunch: '3-7 days',
    timeToFirstRevenue: '6-12 weeks',
    automationSuitability: 95,
    dailyPromoSuitability: 90,
    contentVelocity: 'high',
    riskLevel: 'low',
    recommendedSiteType: 'content_hub',
    recommendedCaptureMethod: 'email_signup',
    trafficChannels: ['YouTube', 'TikTok', 'Instagram Reels', 'Pinterest'],
    monetizationPaths: ['Ad revenue', 'Affiliate links', 'Sponsorships', 'Digital products'],
    canOperateBeforeFiling: true,
  },
  {
    category: 'ecommerce_dropship',
    label: 'E-commerce / Dropshipping',
    description: 'Online store selling physical products via dropshipping, print-on-demand, or lightweight inventory.',
    startupCostRange: [200, 1000],
    timeToLaunch: '1-2 weeks',
    timeToFirstRevenue: '1-3 weeks',
    automationSuitability: 70,
    dailyPromoSuitability: 60,
    contentVelocity: 'medium',
    riskLevel: 'medium',
    recommendedSiteType: 'storefront',
    recommendedCaptureMethod: 'email_signup',
    trafficChannels: ['Facebook Ads', 'TikTok Ads', 'Instagram', 'Google Shopping', 'SEO'],
    monetizationPaths: ['Product sales', 'Upsells', 'Email remarketing'],
    canOperateBeforeFiling: false,
  },
  {
    category: 'saas_micro',
    label: 'Micro SaaS',
    description: 'Small software tool or API solving a niche problem, operated as a subscription service.',
    startupCostRange: [100, 500],
    timeToLaunch: '2-4 weeks',
    timeToFirstRevenue: '4-8 weeks',
    automationSuitability: 80,
    dailyPromoSuitability: 50,
    contentVelocity: 'low',
    riskLevel: 'medium',
    recommendedSiteType: 'landing_page',
    recommendedCaptureMethod: 'waitlist',
    trafficChannels: ['Product Hunt', 'Indie Hackers', 'X/Twitter', 'SEO', 'Hacker News'],
    monetizationPaths: ['Monthly subscriptions', 'Freemium upsell', 'Lifetime deals'],
    canOperateBeforeFiling: true,
  },
  {
    category: 'service_agency',
    label: 'Service / Agency',
    description: 'Freelance or agency model offering a specific skill (design, writing, marketing, development) as a service.',
    startupCostRange: [0, 300],
    timeToLaunch: '3-7 days',
    timeToFirstRevenue: '1-3 weeks',
    automationSuitability: 50,
    dailyPromoSuitability: 55,
    contentVelocity: 'low',
    riskLevel: 'low',
    recommendedSiteType: 'portfolio',
    recommendedCaptureMethod: 'contact_form',
    trafficChannels: ['LinkedIn', 'Upwork', 'Cold outreach', 'Referrals', 'SEO'],
    monetizationPaths: ['Project fees', 'Retainers', 'Productized services'],
    canOperateBeforeFiling: true,
  },
  {
    category: 'affiliate_niche',
    label: 'Affiliate / Niche Site',
    description: 'Content-driven website or channel focused on a niche topic, monetized through affiliate commissions and display ads.',
    startupCostRange: [50, 300],
    timeToLaunch: '1-2 weeks',
    timeToFirstRevenue: '6-12 weeks',
    automationSuitability: 85,
    dailyPromoSuitability: 70,
    contentVelocity: 'high',
    riskLevel: 'low',
    recommendedSiteType: 'blog',
    recommendedCaptureMethod: 'email_signup',
    trafficChannels: ['SEO', 'Pinterest', 'YouTube', 'Reddit', 'Quora'],
    monetizationPaths: ['Affiliate commissions', 'Display ads', 'Sponsored posts', 'Digital products'],
    canOperateBeforeFiling: true,
  },
  {
    category: 'community_membership',
    label: 'Community / Membership',
    description: 'Paid or free community around a topic or skill, monetized through membership fees, courses, or premium content.',
    startupCostRange: [0, 200],
    timeToLaunch: '1-2 weeks',
    timeToFirstRevenue: '4-8 weeks',
    automationSuitability: 65,
    dailyPromoSuitability: 70,
    contentVelocity: 'medium',
    riskLevel: 'low',
    recommendedSiteType: 'membership',
    recommendedCaptureMethod: 'community_join',
    trafficChannels: ['X/Twitter', 'Reddit', 'LinkedIn', 'YouTube', 'Referrals'],
    monetizationPaths: ['Membership fees', 'Premium tiers', 'Courses', 'Events'],
    canOperateBeforeFiling: true,
  },
  {
    category: 'local_lead_gen',
    label: 'Local Lead Generation',
    description: 'Website or landing page that captures leads for local businesses (plumbers, dentists, lawyers) and sells the leads.',
    startupCostRange: [100, 500],
    timeToLaunch: '1-2 weeks',
    timeToFirstRevenue: '2-4 weeks',
    automationSuitability: 75,
    dailyPromoSuitability: 50,
    contentVelocity: 'low',
    riskLevel: 'medium',
    recommendedSiteType: 'landing_page',
    recommendedCaptureMethod: 'contact_form',
    trafficChannels: ['Google Ads', 'SEO', 'Facebook Ads', 'Google Business Profile'],
    monetizationPaths: ['Lead sales', 'Retainer contracts', 'Revenue share'],
    canOperateBeforeFiling: false,
  },
] as const;

/** Look up a category config by its key. */
export function getCategoryConfig(category: string): VentureCategoryConfig | undefined {
  return VENTURE_CATALOG.find(c => c.category === category);
}

/** Return all categories that can start within a given budget. */
export function getCategoriesForBudget(budget: number): VentureCategoryConfig[] {
  return VENTURE_CATALOG.filter(c => c.startupCostRange[0] <= budget);
}
