// ── applyUnrealMilestone4.ts — Milestone 4 Project File Generator ─────────────
//
// Phase 4, Step 5: Fourth real project modification helper.
//
// Writes Milestone 4 implementation artifacts into <projectRoot>/TriForge/.
// Covers the enemy/combat layer: archetype definitions, combat config, and
// detection/aggro shell config. All content adapts to scaffold signals
// (survival/sci-fi/horror/default) detected from the prototype goal and
// scaffold categories.
//
// TRULY IMPLEMENTED:
//   - M4_EnemyCombat_Setup.md      — human-readable M4 implementation guide
//   - M4_EnemyArchetypes.json      — enemy archetype definitions (scaffold-adaptive)
//   - M4_CombatConfig.json         — foundational combat tuning config
//   - M4_DetectionAggroConfig.json — sight/hearing/chase/aggro shell config
//   - M4_Manifest.json             — machine-readable manifest with M3 dependency link
//
// NEXT STEPS (done by developer in Unreal Editor):
//   - Create BP_EnemyBase using specs in M4_EnemyArchetypes.json
//   - Attach Behavior Tree using sight/hearing ranges from M4_DetectionAggroConfig.json
//   - Wire combat stats from M4_CombatConfig.json to character Blueprint properties

import fs   from 'fs';
import path from 'path';
import type { UnrealScaffoldResult }  from '@triforge/engine';
import type { UnrealMilestoneResult } from '@triforge/engine';
import { validateMilestoneBatch }     from './unrealMilestoneValidator';
import { buildMilestone4PythonScript } from './unrealMilestonePython';

// ── Output types ──────────────────────────────────────────────────────────────

export interface M4AppliedFile {
  absolutePath: string;
  relativePath: string;
  description: string;
}

export interface M4ApplicationResult {
  ok: boolean;
  projectRoot: string;
  triforgeDir: string;
  appliedFiles: M4AppliedFile[];
  warnings: string[];
  errors: string[];
}

// ── Scaffold signal helpers ───────────────────────────────────────────────────

function hasEnemyItems(scaffold: UnrealScaffoldResult): boolean {
  return scaffold.scaffoldItems.some(i => i.category === 'enemy');
}

function hasSurvivalItems(scaffold: UnrealScaffoldResult): boolean {
  return scaffold.scaffoldItems.some(i => i.category === 'survival');
}

function isSurvivalGoal(scaffold: UnrealScaffoldResult): boolean {
  const lower = scaffold.prototypeGoal.toLowerCase();
  return /survival|survive|hunger|thirst|zombie|infected|creature/.test(lower) || hasSurvivalItems(scaffold);
}

function isSciFiGoal(scaffold: UnrealScaffoldResult): boolean {
  const lower = scaffold.prototypeGoal.toLowerCase();
  return /sci.fi|scifi|space|robot|drone|mech|futur|cyber|alien/.test(lower);
}

function isHorrorGoal(scaffold: UnrealScaffoldResult): boolean {
  const lower = scaffold.prototypeGoal.toLowerCase();
  return /horror|stalker|monster|brute|terror|haunt|dark/.test(lower);
}

function detectCombatTheme(scaffold: UnrealScaffoldResult): 'survival' | 'scifi' | 'horror' | 'default' {
  if (isSurvivalGoal(scaffold)) return 'survival';
  if (isSciFiGoal(scaffold))    return 'scifi';
  if (isHorrorGoal(scaffold))   return 'horror';
  return 'default';
}

// ── File content builders ─────────────────────────────────────────────────────

function buildSetupMarkdown(
  projectName: string,
  scaffold: UnrealScaffoldResult,
  milestone: UnrealMilestoneResult,
  generatedAt: string,
  m1Present: boolean,
  m2Present: boolean,
  m3Present: boolean,
): string {
  const m5     = milestone.milestones.find(m => m.id === 'M5');
  const steps  = m5?.steps ?? [];
  const theme  = detectCombatTheme(scaffold);

  const themeLabel: Record<typeof theme, string> = {
    survival: 'Creature / Infected',
    scifi:    'Drone / Raider / Armored Unit',
    horror:   'Stalker / Brute / Swarm',
    default:  'Melee Grunt / Ranged / Heavy',
  };

  const stepsMarkdown = steps.length > 0
    ? steps.map((s, i) => `### ${i + 1}. ${s.name}\n${s.description}\n`).join('\n')
    : '> Enemy/combat implementation steps derived from prototype goal.';

  const chainWarnings: string[] = [];
  if (!m1Present) chainWarnings.push('⚠ M1_Manifest.json not found — ensure Milestone 1 (Foundation) was applied.');
  if (!m2Present) chainWarnings.push('⚠ M2_Manifest.json not found — ensure Milestone 2 (Primary Loop / HUD) was applied.');
  if (!m3Present) chainWarnings.push('⚠ M3_Manifest.json not found — ensure Milestone 3 (Supporting Systems) was applied.');

  return `# TriForge — Milestone 4: Enemy / Combat Systems

**Project:** ${projectName}
**Prototype Goal:** ${scaffold.prototypeGoal}
**Combat Theme:** ${themeLabel[theme]}
**Enemy Scaffold Detected:** ${hasEnemyItems(scaffold) ? 'Yes' : 'No (using default archetypes)'}
**Generated:** ${generatedAt}
**Generated by:** TriForge pack.unreal-m4-execute (Phase 4, Step 5)
**Depends on:** M1 (Foundation), M2 (Primary Loop), M3 (Supporting Systems)

${chainWarnings.length > 0 ? `---\n\n## Chain Integrity Warnings\n\n${chainWarnings.join('\n')}\n` : ''}
---

## Milestone Goal

${m5?.goal ?? 'Implement the first enemy/combat layer so the prototype has a real opposition loop — at least one enemy archetype with damage exchange and basic detection behavior.'}

---

## Implementation Steps

${stepsMarkdown}

---

## Enemy Base Class (BP_EnemyBase)

Create an Actor Blueprint named **BP_EnemyBase** in \`Content/Enemies/\`.
This is the parent class all specific enemy archetypes inherit from.

### Required components

| Component              | Type              | Purpose                                   |
|----------------------- |------------------ |------------------------------------------ |
| CapsuleComponent       | UCapsuleComponent | Root collision — physics and overlap       |
| SkeletalMeshComponent  | USkeletalMesh     | Enemy visual mesh                          |
| BP_HealthComponent     | (from M2)         | Health/death using M2 health system        |
| PawnSensingComponent   | UPawnSensing      | Built-in sight/hearing detection           |

### Required variables

| Variable           | Type    | Default | Notes                                       |
|------------------- |-------- |-------- |-------------------------------------------- |
| MaxHealth          | Float   | 100.0   | Override per archetype                      |
| MovementSpeed      | Float   | 300.0   | Override per archetype                      |
| AttackDamage       | Float   | 15.0    | Override per archetype                      |
| AttackRange        | Float   | 150.0   | Melee range; ignored for ranged archetypes  |
| bIsAlerted         | Boolean | false   | True when enemy has detected the player     |
| CurrentTarget      | AActor* | null    | Reference to the actor being chased/attacked|

### Required events / functions

| Name                   | Description                                                       |
|----------------------- |------------------------------------------------------------------ |
| OnSeePawn(Pawn)        | Fired by PawnSensing — set bIsAlerted, assign CurrentTarget       |
| OnHearNoise(...)       | Fired by PawnSensing — alert if not already alerted               |
| ChaseTarget()          | Move toward CurrentTarget using MoveToActor (AI)                  |
| TryAttack()            | If in range, apply damage to CurrentTarget via TakeDamage()       |
| Die()                  | Play death anim, disable collision, destroy after delay           |
| LoseTarget()           | Clear bIsAlerted + CurrentTarget after chase timeout              |

---

## Damage Integration (M2 Bridge)

M4 enemies should use the **M2 health system** (BP_HealthComponent):

- Enemy \`TryAttack()\` should call \`UGameplayStatics::ApplyDamage()\` on the player
- Player character should forward \`TakeDamage()\` events to \`BP_HealthComponent::TakeDamage()\`
- This connects M4 enemy attacks to M2 HUD health display automatically

See \`M4_CombatConfig.json\` for damage values per archetype.

---

## Archetype Blueprints

See \`M4_EnemyArchetypes.json\` for the full archetype spec.

For each archetype, create a child Blueprint of \`BP_EnemyBase\`:

| Blueprint         | Content Path         | Notes                            |
|------------------ |--------------------- |--------------------------------- |
| BP_Enemy_Grunt    | Content/Enemies/     | Melee attacker — close range     |
| BP_Enemy_Ranged   | Content/Enemies/     | Ranged — keeps distance          |
| BP_Enemy_Heavy    | Content/Enemies/     | High health, slow, hard-hitting  |

Override the parent variables (MaxHealth, AttackDamage, MovementSpeed) per archetype.

---

## Detection & Aggro (AI Controller)

See \`M4_DetectionAggroConfig.json\` for all detection parameters.

### Setup steps

1. Create **BP_EnemyAIController** (AI Controller Blueprint) in \`Content/AI/\`.
2. In BP_EnemyBase, set **AIControllerClass = BP_EnemyAIController**.
3. In BP_EnemyBase \`BeginPlay\`, call \`SpawnDefaultController()\` if not already controlled.
4. Wire \`PawnSensing::OnSeePawn\` → \`BP_EnemyBase::OnSeePawn\`.
5. Wire \`PawnSensing::OnHearNoise\` → \`BP_EnemyBase::OnHearNoise\`.
6. Implement a simple \`Tick\`-driven state machine in BP_EnemyBase:
   - State: **Idle** — patrol or stand (use NavMesh random point if available)
   - State: **Alerted** — chase CurrentTarget via \`MoveToActor\`
   - State: **Attacking** — stop movement, call \`TryAttack()\` on timer
   - State: **LostTarget** — wait \`ChaseTimeoutSec\`, then return to Idle

> This is a simple Tick-based state machine, NOT a full Behavior Tree.
> A Behavior Tree can be added in a later milestone once the loop is proven.

---

## Encounter Setup

Place enemy instances in the world via the **World Outliner**:

1. Drag \`BP_Enemy_Grunt\` (or other archetype) into the level.
2. Ensure a **NavMesh Volume** covers the play area (required for MoveToActor).
3. Verify \`AI Controller Class\` is set to \`BP_EnemyAIController\` on each placed instance.
4. Optionally use a simple spawn volume (\`BP_EnemySpawner\`) to spawn enemies on BeginPlay.

---

## Notes & Assumptions

- BP_HealthComponent (from M2) must be on BP_PlayerCharacter for damage to register correctly.
- PawnSensing uses line-of-sight checks — ensure the enemy mesh has a valid collision capsule.
- MoveToActor requires a NavMesh — add a NavMeshBoundsVolume to the level and rebuild nav.
- AttackRange is the melee range; ranged archetypes should use a projectile instead of direct damage.
- Do NOT use deprecated AIMoveTo paths — use UPathFollowingComponent or AIController::MoveToActor.

---

## Next Steps After M4

1. Create BP_EnemyBase with all required components and variables.
2. Create BP_EnemyAIController.
3. Create archetype child Blueprints (BP_Enemy_Grunt, BP_Enemy_Ranged, BP_Enemy_Heavy).
4. Place enemies in a test level and verify detection + chase + attack loop.
5. Verify M2 health bar decreases when enemy attacks the player.
${isSurvivalGoal(scaffold) ? '6. Verify loot items (M3) drop on enemy death — requires BP_WorldItem pickup.\n' : ''}\
${!isSurvivalGoal(scaffold) ? '6' : '7'}. Run \`pack.unreal-build\` to verify M1+M2+M3+M4 systems compile cleanly.
${!isSurvivalGoal(scaffold) ? '7' : '8'}. When M4 loop is stable, proceed to Milestone 5 (Progression / Save Systems).

---

*This file was generated by TriForge and can be safely edited.*
`;
}

function buildEnemyArchetypesJson(
  projectName: string,
  scaffold: UnrealScaffoldResult,
  generatedAt: string,
): string {
  const theme = detectCombatTheme(scaffold);

  type Archetype = {
    id: string;
    displayName: string;
    role: string;
    parentBlueprint: string;
    contentPath: string;
    health: number;
    movementSpeedCmSec: number;
    attackDamage: number;
    attackRangeCm: number;
    attackType: 'melee' | 'ranged' | 'melee_heavy';
    threatLevel: 'low' | 'medium' | 'high';
    movementStyle: string;
    lootTableHint: string;
    notes: string;
  };

  const archetypesByTheme: Record<typeof theme, Archetype[]> = {
    survival: [
      {
        id:                 'enemy.infected_shambler',
        displayName:        'Infected Shambler',
        role:               'Basic melee threat — slow but relentless',
        parentBlueprint:    'BP_EnemyBase',
        contentPath:        'Content/Enemies/',
        health:             60,
        movementSpeedCmSec: 200,
        attackDamage:       10,
        attackRangeCm:      120,
        attackType:         'melee',
        threatLevel:        'low',
        movementStyle:      'Slow shamble toward target; no pathfinding shortcuts',
        lootTableHint:      'small_consumable',
        notes:              'Easy first encounter. Overwhelm in groups for scaling difficulty.',
      },
      {
        id:                 'enemy.infected_runner',
        displayName:        'Infected Runner',
        role:               'Fast melee threat — flanks and rushes',
        parentBlueprint:    'BP_EnemyBase',
        contentPath:        'Content/Enemies/',
        health:             40,
        movementSpeedCmSec: 500,
        attackDamage:       15,
        attackRangeCm:      110,
        attackType:         'melee',
        threatLevel:        'medium',
        movementStyle:      'Sprint directly at player; high aggro radius',
        lootTableHint:      'none',
        notes:              'Dangerous at close range. Countered by ranged weapons or obstacles.',
      },
      {
        id:                 'enemy.infected_brute',
        displayName:        'Infected Brute',
        role:               'Tanky heavy — absorbs damage and closes distance',
        parentBlueprint:    'BP_EnemyBase',
        contentPath:        'Content/Enemies/',
        health:             200,
        movementSpeedCmSec: 180,
        attackDamage:       35,
        attackRangeCm:      160,
        attackType:         'melee_heavy',
        threatLevel:        'high',
        movementStyle:      'Slow charge; knockback on hit',
        lootTableHint:      'resource_bundle',
        notes:              'Mini-boss tier. Should be rare. Requires kiting or concentrated fire.',
      },
    ],
    scifi: [
      {
        id:                 'enemy.patrol_drone',
        displayName:        'Patrol Drone',
        role:               'Ranged threat — hovers and fires energy projectiles',
        parentBlueprint:    'BP_EnemyBase',
        contentPath:        'Content/Enemies/',
        health:             50,
        movementSpeedCmSec: 350,
        attackDamage:       12,
        attackRangeCm:      800,
        attackType:         'ranged',
        threatLevel:        'low',
        movementStyle:      'Hover at mid-range; strafe laterally while attacking',
        lootTableHint:      'ammo',
        notes:              'Best countered by closing distance quickly or using cover.',
      },
      {
        id:                 'enemy.raider_grunt',
        displayName:        'Raider Grunt',
        role:               'Melee/ranged hybrid — advances under fire',
        parentBlueprint:    'BP_EnemyBase',
        contentPath:        'Content/Enemies/',
        health:             80,
        movementSpeedCmSec: 320,
        attackDamage:       18,
        attackRangeCm:      600,
        attackType:         'ranged',
        threatLevel:        'medium',
        movementStyle:      'Advance toward player while firing; cover-seeking if available',
        lootTableHint:      'ammo_and_credits',
        notes:              'Core encounter enemy. Mix with drones for varied combat.',
      },
      {
        id:                 'enemy.armored_heavy',
        displayName:        'Armored Heavy',
        role:               'High-health tank — absorbs damage and suppresses',
        parentBlueprint:    'BP_EnemyBase',
        contentPath:        'Content/Enemies/',
        health:             250,
        movementSpeedCmSec: 200,
        attackDamage:       30,
        attackRangeCm:      400,
        attackType:         'ranged',
        threatLevel:        'high',
        movementStyle:      'Advance slowly; suppression fire prevents player movement',
        lootTableHint:      'high_tier_loot',
        notes:              'Requires flanking or high-damage weapons to defeat efficiently.',
      },
    ],
    horror: [
      {
        id:                 'enemy.stalker',
        displayName:        'Stalker',
        role:               'Stealth threat — follows at distance until close',
        parentBlueprint:    'BP_EnemyBase',
        contentPath:        'Content/Enemies/',
        health:             70,
        movementSpeedCmSec: 280,
        attackDamage:       25,
        attackRangeCm:      130,
        attackType:         'melee',
        threatLevel:        'medium',
        movementStyle:      'Circle player at outer detection edge; rush when close',
        lootTableHint:      'none',
        notes:              'Designed to create tension before attack. Disable audio cues to increase fear.',
      },
      {
        id:                 'enemy.brute',
        displayName:        'Brute',
        role:               'Powerful melee — charges and stuns on hit',
        parentBlueprint:    'BP_EnemyBase',
        contentPath:        'Content/Enemies/',
        health:             180,
        movementSpeedCmSec: 240,
        attackDamage:       40,
        attackRangeCm:      170,
        attackType:         'melee_heavy',
        threatLevel:        'high',
        movementStyle:      'Charge in straight line; destroys obstacles',
        lootTableHint:      'key_item',
        notes:              'Use as a set-piece encounter. Should be rare and memorable.',
      },
      {
        id:                 'enemy.swarm_unit',
        displayName:        'Swarm Unit',
        role:               'Weak individually; dangerous in groups of 5+',
        parentBlueprint:    'BP_EnemyBase',
        contentPath:        'Content/Enemies/',
        health:             20,
        movementSpeedCmSec: 400,
        attackDamage:       5,
        attackRangeCm:      90,
        attackType:         'melee',
        threatLevel:        'low',
        movementStyle:      'Rush in a pack; surround player',
        lootTableHint:      'none',
        notes:              'Spawn in groups of 4–8. Area damage (grenades) required for efficient clearance.',
      },
    ],
    default: [
      {
        id:                 'enemy.melee_grunt',
        displayName:        'Melee Grunt',
        role:               'Basic melee attacker — the prototype\'s default enemy',
        parentBlueprint:    'BP_EnemyBase',
        contentPath:        'Content/Enemies/',
        health:             80,
        movementSpeedCmSec: 300,
        attackDamage:       15,
        attackRangeCm:      140,
        attackType:         'melee',
        threatLevel:        'low',
        movementStyle:      'Direct path toward player; no special behavior',
        lootTableHint:      'small_resource',
        notes:              'First enemy the player should encounter. Easy to read, predictable.',
      },
      {
        id:                 'enemy.ranged_threat',
        displayName:        'Ranged Threat',
        role:               'Fires from distance — forces player to close or take cover',
        parentBlueprint:    'BP_EnemyBase',
        contentPath:        'Content/Enemies/',
        health:             60,
        movementSpeedCmSec: 260,
        attackDamage:       12,
        attackRangeCm:      700,
        attackType:         'ranged',
        threatLevel:        'medium',
        movementStyle:      'Maintain distance; back away when player closes',
        lootTableHint:      'ammo',
        notes:              'Pair with melee grunts to force the player to manage range.',
      },
      {
        id:                 'enemy.heavy_tank',
        displayName:        'Heavy Tank',
        role:               'High health, slow, hard-hitting — area control enemy',
        parentBlueprint:    'BP_EnemyBase',
        contentPath:        'Content/Enemies/',
        health:             220,
        movementSpeedCmSec: 170,
        attackDamage:       35,
        attackRangeCm:      155,
        attackType:         'melee_heavy',
        threatLevel:        'high',
        movementStyle:      'Slow advance; wide hit arc',
        lootTableHint:      'resource_bundle',
        notes:              'Use sparingly. Should feel like a sub-boss encounter.',
      },
    ],
  };

  const archetypes = archetypesByTheme[theme];

  return JSON.stringify({
    triforgeVersion: '1.0',
    milestone:       'M4',
    project:         projectName,
    prototypeGoal:   scaffold.prototypeGoal,
    combatTheme:     theme,
    generatedAt,
    instructions: [
      'Create BP_EnemyBase (Actor Blueprint) in Content/Enemies/ as the parent class.',
      'Add BP_HealthComponent (from M2), UCapsuleComponent, USkeletalMesh, and UPawnSensing.',
      'For each archetype below, create a child Blueprint of BP_EnemyBase.',
      'Override MaxHealth, MovementSpeed, AttackDamage, AttackRange, and AttackType per archetype.',
      'See M4_EnemyCombat_Setup.md for full setup steps and component wiring.',
    ],
    baseBlueprint: {
      name:        'BP_EnemyBase',
      parentClass: 'Character',
      contentPath: 'Content/Enemies/',
    },
    archetypes,
  }, null, 2);
}

function buildCombatConfigJson(
  projectName: string,
  scaffold: UnrealScaffoldResult,
  generatedAt: string,
): string {
  const theme = detectCombatTheme(scaffold);

  const damageScaling: Record<typeof theme, { playerBase: number; enemyBase: number; heavyMultiplier: number }> = {
    survival: { playerBase: 25, enemyBase: 10, heavyMultiplier: 3.5 },
    scifi:    { playerBase: 20, enemyBase: 12, heavyMultiplier: 2.5 },
    horror:   { playerBase: 30, enemyBase: 20, heavyMultiplier: 2.0 },
    default:  { playerBase: 20, enemyBase: 15, heavyMultiplier: 2.5 },
  };

  const scaling = damageScaling[theme];

  return JSON.stringify({
    triforgeVersion: '1.0',
    milestone:       'M4',
    project:         projectName,
    prototypeGoal:   scaffold.prototypeGoal,
    combatTheme:     theme,
    generatedAt,
    instructions: [
      'Use these values as starting points — tune via playtesting.',
      'Apply playerDamageBase as the default damage for the player\'s primary attack.',
      'Enemy damage values are set per-archetype in M4_EnemyArchetypes.json.',
      'Use UGameplayStatics::ApplyDamage() for all damage application — never call TakeDamage() directly.',
      'heavyEnemyDamageMultiplier applies to melee_heavy archetype attacks only.',
    ],
    playerCombat: {
      damageBase:           scaling.playerBase,
      attackRangeCm:        200,
      attackCooldownSec:    0.5,
      criticalHitChance:    0.0,
      criticalHitMultiplier: 2.0,
      notes: 'criticalHit disabled for prototype — enable in M5 or later.',
    },
    enemyCombat: {
      damageBase:             scaling.enemyBase,
      heavyDamageMultiplier:  scaling.heavyMultiplier,
      attackCooldownSec:      1.2,
      rangedProjectileSpeed:  1200,
      hitReactionEnabled:     true,
      staggerThreshold:       0.3,
      notes: 'staggerThreshold = 30% of max health in single hit triggers stagger anim.',
    },
    healthScaling: {
      playerStartHealth:  100,
      enemyBaseHealth:    80,
      heavyHealthMultiplier: 2.5,
      notes: 'Archetype health values in M4_EnemyArchetypes.json override enemyBaseHealth.',
    },
    weaponDamageCategories: [
      { id: 'melee',       label: 'Melee',         damageMultiplier: 1.0 },
      { id: 'melee_heavy', label: 'Heavy Melee',    damageMultiplier: scaling.heavyMultiplier },
      { id: 'ranged',      label: 'Ranged / Bullet', damageMultiplier: 0.8 },
      { id: 'explosive',   label: 'Explosive',       damageMultiplier: 2.0, aoeRadiusCm: 300 },
    ],
    prototypeBalancingNotes: [
      'Start with player health at 100 and enemy damage at base values.',
      'Tune up/down by 20% increments during playtesting.',
      'Goal: player should survive ~5 melee hits from a grunt before dying.',
      `Combat theme: ${theme} — adjust damage feel to match genre expectations.`,
    ],
  }, null, 2);
}

function buildDetectionAggroConfigJson(
  projectName: string,
  scaffold: UnrealScaffoldResult,
  generatedAt: string,
): string {
  const theme = detectCombatTheme(scaffold);

  const detectionByTheme: Record<typeof theme, {
    sightRange: number; sightAngle: number; hearingRange: number;
    chaseRadius: number; loseTargetSec: number; aggroStyle: string;
  }> = {
    survival: {
      sightRange:    600,  sightAngle:  90,
      hearingRange:  300,  chaseRadius: 800,
      loseTargetSec: 8,
      aggroStyle:    'Hearing-dominant — infected react to noise even without line of sight',
    },
    scifi: {
      sightRange:    1200, sightAngle:  60,
      hearingRange:  200,  chaseRadius: 1500,
      loseTargetSec: 5,
      aggroStyle:    'Sight-dominant — units use sensors; hearing is secondary',
    },
    horror: {
      sightRange:    400,  sightAngle:  70,
      hearingRange:  500,  chaseRadius: 600,
      loseTargetSec: 15,
      aggroStyle:    'Persistent tracker — loses target slowly; creates dread',
    },
    default: {
      sightRange:    800,  sightAngle:  80,
      hearingRange:  350,  chaseRadius: 1000,
      loseTargetSec: 6,
      aggroStyle:    'Balanced sight and hearing — standard action game feel',
    },
  };

  const det = detectionByTheme[theme];

  return JSON.stringify({
    triforgeVersion: '1.0',
    milestone:       'M4',
    project:         projectName,
    prototypeGoal:   scaffold.prototypeGoal,
    combatTheme:     theme,
    generatedAt,
    instructions: [
      'Configure UPawnSensing component on BP_EnemyBase using these values.',
      'Wire OnSeePawn and OnHearNoise events to BP_EnemyBase custom events.',
      'Implement a simple Idle→Alerted→Attacking→LostTarget state machine in BP_EnemyBase Tick.',
      'Use MoveToActor (AIController) for chase — requires a NavMeshBoundsVolume in the level.',
      'See M4_EnemyCombat_Setup.md for the full state machine setup instructions.',
    ],
    detection: {
      sightRangeCm:       det.sightRange,
      sightAngleDeg:      det.sightAngle,
      hearingRangeCm:     det.hearingRange,
      requireLineOfSight: true,
      notes:              det.aggroStyle,
    },
    chase: {
      chaseRadiusCm:          det.chaseRadius,
      loseTargetTimeoutSec:   det.loseTargetSec,
      chaseMovementSpeedBoost: 1.1,
      notes:                  'Speed boost applies during chase state only.',
    },
    aggroStates: [
      {
        id:          'idle',
        label:       'Idle',
        description: 'Enemy is unaware. Patrol or stand. Transitions to Alerted on detect.',
        transitions: ['→ Alerted: OnSeePawn or OnHearNoise fires'],
      },
      {
        id:          'alerted',
        label:       'Alerted',
        description: 'Enemy has detected the player. Chase via MoveToActor.',
        transitions: [
          '→ Attacking: distance ≤ AttackRange',
          `→ LostTarget: no line-of-sight for ${det.loseTargetSec}s`,
        ],
      },
      {
        id:          'attacking',
        label:       'Attacking',
        description: 'Enemy is in range. Stop movement and trigger attack on timer.',
        transitions: [
          '→ Alerted: target moves out of AttackRange',
          '→ Idle: target dies or is destroyed',
        ],
      },
      {
        id:          'lost_target',
        label:       'Lost Target',
        description: `Wait ${det.loseTargetSec}s at last known position, then return to Idle.`,
        transitions: [
          '→ Alerted: re-detects player during timeout',
          '→ Idle: timeout expires',
        ],
      },
    ],
    encounterTriggers: [
      {
        id:          'on_sight',
        description: 'Enemy sees player — trigger Alerted immediately.',
        condition:   'OnSeePawn(Player)',
      },
      {
        id:          'on_noise',
        description: 'Player makes noise (footsteps, gunshot) — trigger Alerted if hearing range.',
        condition:   'OnHearNoise within hearingRangeCm',
      },
      {
        id:          'on_damage',
        description: 'Enemy takes damage — trigger Alerted regardless of sight/hearing.',
        condition:   'TakeDamage event fires',
      },
    ],
    navMeshRequirement:
      'A NavMeshBoundsVolume must cover the play area and nav must be built before MoveToActor works.',
  }, null, 2);
}

// ── Main application function ─────────────────────────────────────────────────

/**
 * Apply Milestone 4 to the active Unreal project by generating structured
 * enemy/combat artifacts into <projectRoot>/TriForge/.
 *
 * @param projectPath      Confirmed .uproject path (high-confidence)
 * @param projectName      Project name
 * @param scaffold         Scaffold result from generateUnrealSystemScaffold()
 * @param milestone        Milestone result from generateUnrealMilestones()
 * @param m1ManifestExists Whether M1_Manifest.json is present (chain signal)
 * @param m2ManifestExists Whether M2_Manifest.json is present (chain signal)
 * @param m3ManifestExists Whether M3_Manifest.json is present (chain signal)
 */
export async function applyUnrealMilestone4(
  projectPath: string,
  projectName: string,
  scaffold: UnrealScaffoldResult,
  milestone: UnrealMilestoneResult,
  m1ManifestExists: boolean,
  m2ManifestExists: boolean,
  m3ManifestExists: boolean,
): Promise<M4ApplicationResult> {
  const projectRoot = path.dirname(projectPath);
  const triforgeDir = path.join(projectRoot, 'TriForge');
  const generatedAt = new Date().toISOString();
  const appliedFiles: M4AppliedFile[] = [];
  const warnings: string[]            = [];
  const errors: string[]              = [];

  if (!m1ManifestExists) {
    warnings.push(
      'M1_Manifest.json was not found in TriForge/ — Milestone 1 (Foundation) may not have been applied yet. ' +
      'M4 artifacts are still written, but review the M1 foundation before implementing M4.',
    );
  }
  if (!m2ManifestExists) {
    warnings.push(
      'M2_Manifest.json was not found in TriForge/ — Milestone 2 (Primary Loop / HUD) may not have been applied yet. ' +
      'M4 enemy attacks will not integrate with the HUD health display until M2 is applied.',
    );
  }
  if (!m3ManifestExists) {
    warnings.push(
      'M3_Manifest.json was not found in TriForge/ — Milestone 3 (Supporting Systems) may not have been applied yet. ' +
      'M4 loot hints reference M3 item types — apply M3 before wiring enemy loot drops.',
    );
  }

  // ── Ensure TriForge directory exists ─────────────────────────────────────
  try {
    fs.mkdirSync(triforgeDir, { recursive: true });
  } catch (e: unknown) {
    const msg = e instanceof Error ? e.message : String(e);
    return {
      ok: false, projectRoot, triforgeDir,
      appliedFiles: [], warnings,
      errors: [`Failed to create TriForge directory at ${triforgeDir}: ${msg}`],
    };
  }

  // ── Write helper ──────────────────────────────────────────────────────────
  function writeFile(filename: string, content: string, description: string): boolean {
    const absolutePath = path.join(triforgeDir, filename);
    const relativePath = path.join('TriForge', filename);
    try {
      fs.writeFileSync(absolutePath, content, 'utf-8');
      appliedFiles.push({ absolutePath, relativePath, description });
      return true;
    } catch (e: unknown) {
      const msg = e instanceof Error ? e.message : String(e);
      warnings.push(`Could not write ${relativePath}: ${msg}`);
      return false;
    }
  }

  // ── Write M4 artifacts ────────────────────────────────────────────────────
  writeFile(
    'M4_EnemyCombat_Setup.md',
    buildSetupMarkdown(projectName, scaffold, milestone, generatedAt, m1ManifestExists, m2ManifestExists, m3ManifestExists),
    'Milestone 4 implementation guide — enemy base class, archetypes, detection/aggro, and M2 damage integration.',
  );

  writeFile(
    'M4_EnemyArchetypes.json',
    buildEnemyArchetypesJson(projectName, scaffold, generatedAt),
    'Enemy archetype definitions — 3 archetypes adapted to prototype goal (survival/sci-fi/horror/default).',
  );

  writeFile(
    'M4_CombatConfig.json',
    buildCombatConfigJson(projectName, scaffold, generatedAt),
    'Foundational combat tuning config — player/enemy damage, health scaling, weapon categories.',
  );

  writeFile(
    'M4_DetectionAggroConfig.json',
    buildDetectionAggroConfigJson(projectName, scaffold, generatedAt),
    'Detection and aggro config — sight/hearing ranges, chase radius, and aggro state machine spec ready to wire.',
  );

  // ── Manifest ──────────────────────────────────────────────────────────────
  const chainIntegrityNotes: string[] = [];
  if (!m1ManifestExists) chainIntegrityNotes.push('M1_Manifest.json missing — M1 foundation may not be applied.');
  if (!m2ManifestExists) chainIntegrityNotes.push('M2_Manifest.json missing — M2 primary loop / HUD may not be applied.');
  if (!m3ManifestExists) chainIntegrityNotes.push('M3_Manifest.json missing — M3 supporting systems may not be applied.');

  const dependsOn: string[] = [];
  if (m3ManifestExists) dependsOn.push('M3_Manifest.json');
  if (m2ManifestExists && !m3ManifestExists) dependsOn.push('M2_Manifest.json');
  if (m1ManifestExists && !m2ManifestExists && !m3ManifestExists) dependsOn.push('M1_Manifest.json');

  const theme = detectCombatTheme(scaffold);
  const manifest = {
    triforgeVersion: '1.0',
    milestone:       'M4',
    project:         projectName,
    projectPath,
    generatedAt,
    packId:          'pack.unreal-m4-execute',
    combatTheme:     theme,
    dependsOn,
    files: appliedFiles.map(f => ({ relativePath: f.relativePath, description: f.description })),
    notes: [
      `Combat theme: ${theme} (derived from prototype goal and scaffold signals)`,
      `Enemy archetypes: 3 defined (${theme === 'survival' ? 'Shambler / Runner / Brute' : theme === 'scifi' ? 'Patrol Drone / Raider / Armored Heavy' : theme === 'horror' ? 'Stalker / Brute / Swarm Unit' : 'Melee Grunt / Ranged Threat / Heavy Tank'})`,
      'M2 integration: enemy attacks route through UGameplayStatics::ApplyDamage → BP_HealthComponent',
      'M3 integration: enemy loot hints reference M3 item types (apply M3 first for full wiring)',
      ...chainIntegrityNotes,
    ],
    recommendedNext: 'pack.unreal-m5-execute',
  };

  writeFile(
    'M4_Manifest.json',
    JSON.stringify(manifest, null, 2),
    'Machine-readable manifest of all M4 generated files for future pack chaining.',
  );

  // Companion Python script — run from Unreal Editor → Tools → Execute Python
  // Script to materialize the M4 enemy/combat scaffolds. Idempotent.
  writeFile(
    'M4_Apply.py',
    buildMilestone4PythonScript(projectName, scaffold, milestone, generatedAt),
    'Companion Python script — runs inside Unreal Editor to create the enemy, ' +
    'AI controller, and damage component scaffolds described above.',
  );

  // ── B5: Post-write validation ──────────────────────────────────────────
  const validation = validateMilestoneBatch(
    appliedFiles.map(f => ({
      absolutePath:      f.absolutePath,
      relativePath:      f.relativePath,
      expectedMilestone: 'M4',
      isManifest:        f.relativePath.endsWith('M4_Manifest.json'),
    })),
  );
  if (validation.failed.length > 0) {
    warnings.push(...validation.warnings);
    const failedPaths = new Set(validation.failed.map(f => f.absolutePath));
    const survivingFiles = appliedFiles.filter(f => !failedPaths.has(f.absolutePath));
    appliedFiles.length = 0;
    appliedFiles.push(...survivingFiles);
  }

  const ok = appliedFiles.length > 0 && errors.length === 0;
  return { ok, projectRoot, triforgeDir, appliedFiles, warnings, errors };
}
