// ── applyUnrealMilestone1.ts — Milestone 1 Project File Generator ─────────────
//
// Phase 4, Step 1: First real project modification helper.
//
// Writes structured implementation artifacts into the active Unreal project.
// These are real files on disk, tied to the confirmed project path, and
// immediately usable by the developer to guide M1 work in Unreal Editor.
//
// TRULY IMPLEMENTED:
//   - TriForge/ directory creation at the project root
//   - M1_Foundation_Setup.md — human-readable M1 implementation guide
//   - M1_InputActions.json   — Enhanced Input action spec for IMC_Default
//   - M1_ProjectConfig.json  — Game mode / player / camera configuration spec
//
// NOT YET:
//   - Blueprint asset generation
//   - C++ file generation
//   - Editor-side asset creation
//   - Input mapping context .uasset creation
//   - Post-write editor reload triggers

import fs   from 'fs';
import path from 'path';
import type { UnrealScaffoldResult }   from '@triforge/engine';
import type { UnrealMilestoneResult }  from '@triforge/engine';
import { validateMilestoneBatch }      from './unrealMilestoneValidator';
import { buildMilestone1PythonScript } from './unrealMilestonePython';

// ── Output types ──────────────────────────────────────────────────────────────

export interface M1AppliedFile {
  /** Absolute path to the written file. */
  absolutePath: string;
  /** Path relative to the project root (for display and artifact records). */
  relativePath: string;
  /** Human-readable description of what the file contains. */
  description: string;
}

export interface M1ApplicationResult {
  ok: boolean;
  /** Project root directory. */
  projectRoot: string;
  /** TriForge working directory inside the project. */
  triforgeDir: string;
  /** Every file that was written successfully. */
  appliedFiles: M1AppliedFile[];
  /** Non-fatal warnings during generation. */
  warnings: string[];
  /** Fatal errors that prevented writing (present when ok === false). */
  errors: string[];
}

// ── Camera mode label ─────────────────────────────────────────────────────────

function cameraLabel(scaffoldItems: UnrealScaffoldResult['scaffoldItems']): string {
  const camItem = scaffoldItems.find(i => i.category === 'camera');
  if (!camItem) return 'Third-Person (assumed)';
  if (/first.person|1st.person|fps/i.test(camItem.name)) return 'First-Person';
  if (/top.down|isometric/i.test(camItem.name)) return 'Top-Down';
  return 'Third-Person';
}

// ── File content builders ─────────────────────────────────────────────────────

function buildSetupMarkdown(
  projectName: string,
  scaffold: UnrealScaffoldResult,
  milestone: UnrealMilestoneResult,
  generatedAt: string,
): string {
  const m1 = milestone.milestones.find(m => m.id === 'M1');
  const m1Steps = m1?.steps ?? [];
  const cam = cameraLabel(scaffold.scaffoldItems);

  const stepsMarkdown = m1Steps.length > 0
    ? m1Steps.map((s, i) =>
        `### ${i + 1}. ${s.name}\n${s.description}\n`
      ).join('\n')
    : '> No specific M1 steps were generated from the scaffold.';

  const assumptions = [
    ...milestone.assumptions,
    ...milestone.warnings,
  ];

  return `# TriForge — Milestone 1: Foundation Setup

**Project:** ${projectName}
**Prototype Goal:** ${scaffold.prototypeGoal}
**Camera Mode:** ${cam}
**Generated:** ${generatedAt}
**Generated by:** TriForge pack.unreal-m1-execute (Phase 4, Step 1)

---

## Milestone Goal

${m1?.goal ?? 'Establish core player character, camera rig, and input mapping.'}

---

## Implementation Steps

${stepsMarkdown}

---

## Enhanced Input Mapping (M1_InputActions.json)

See the companion file \`TriForge/M1_InputActions.json\` for the structured
Enhanced Input action spec. Create an **Input Mapping Context** named
\`IMC_Default\` in \`Content/Input/\` and add each listed action.

### Minimum Required Actions

| Action Name  | Value Type | Description                          |
|------------- |----------- |------------------------------------- |
| IA_Move      | Axis2D     | Player movement (WASD / left stick)  |
| IA_Look      | Axis2D     | Camera look (mouse / right stick)    |
| IA_Jump      | Digital    | Jump (Space / face button South)     |
| IA_Interact  | Digital    | World interaction (E / face button East) |

---

## Project Configuration (M1_ProjectConfig.json)

See \`TriForge/M1_ProjectConfig.json\` for the full specification.

### Key Assets to Create

| Asset                   | Class                  | Location           |
|------------------------ |----------------------- |------------------- |
| BP_GameMode             | AGameMode              | Content/Core/      |
| BP_GameState            | AGameState             | Content/Core/      |
| BP_PlayerCharacter      | ACharacter             | Content/Player/    |
| BP_PlayerController     | APlayerController      | Content/Player/    |
| L_TestArena             | UWorld                 | Content/Maps/      |
| IMC_Default             | UInputMappingContext   | Content/Input/     |

---

## Notes & Assumptions

${assumptions.length > 0
  ? assumptions.map(a => `- ${a}`).join('\n')
  : '- No special assumptions were recorded for this milestone.'}

---

## Next Steps After M1

1. Create the assets listed in the configuration table above in Unreal Editor.
2. Set \`BP_GameMode\` as the default game mode in Project Settings → Maps & Modes.
3. Set \`BP_PlayerCharacter\` as the default pawn class in \`BP_GameMode\`.
4. Run \`pack.unreal-build\` to verify the project compiles cleanly.
5. When M1 is stable, proceed to Milestone 2 via \`pack.unreal-m2-execute\`.

---

*This file was generated by TriForge and can be safely edited. It will be
overwritten if you run \`pack.unreal-m1-execute\` again.*
`;
}

function buildInputActionsJson(
  projectName: string,
  scaffold: UnrealScaffoldResult,
  generatedAt: string,
): string {
  const cam = cameraLabel(scaffold.scaffoldItems);
  const hasInventory = scaffold.scaffoldItems.some(i => i.category === 'inventory');

  const actions: Array<{
    name: string;
    valueType: string;
    triggerType: string;
    description: string;
    suggestedBindings: string[];
  }> = [
    {
      name: 'IA_Move',
      valueType: 'Axis2D',
      triggerType: 'Down',
      description: 'Player movement on the XY plane.',
      suggestedBindings: ['W/A/S/D keys (with swizzle)', 'Gamepad left stick'],
    },
    {
      name: 'IA_Look',
      valueType: 'Axis2D',
      triggerType: 'Down',
      description: cam === 'First-Person'
        ? 'First-person camera look (pitch/yaw).'
        : 'Camera orbit / look input (pitch/yaw).',
      suggestedBindings: ['Mouse XY delta', 'Gamepad right stick'],
    },
    {
      name: 'IA_Jump',
      valueType: 'Digital',
      triggerType: 'Pressed',
      description: 'Character jump.',
      suggestedBindings: ['Space bar', 'Gamepad face button South (A/Cross)'],
    },
    {
      name: 'IA_Interact',
      valueType: 'Digital',
      triggerType: 'Pressed',
      description: 'World interaction / use.',
      suggestedBindings: ['E key', 'Gamepad face button East (B/Circle)'],
    },
  ];

  if (hasInventory) {
    actions.push({
      name: 'IA_OpenInventory',
      valueType: 'Digital',
      triggerType: 'Pressed',
      description: 'Toggle the inventory screen.',
      suggestedBindings: ['I key', 'Gamepad Options / Menu button'],
    });
  }

  return JSON.stringify({
    triforgeVersion: '1.0',
    milestone: 'M1',
    project: projectName,
    prototypeGoal: scaffold.prototypeGoal,
    generatedAt,
    instructions: [
      'Create a new Input Mapping Context asset named IMC_Default in Content/Input/.',
      'Add each action below as an Input Action asset in Content/Input/Actions/.',
      'Add the listed bindings to IMC_Default.',
      'Assign IMC_Default in your BP_PlayerController BeginPlay via AddMappingContext.',
    ],
    inputMappingContext: 'IMC_Default',
    suggestedContentPath: 'Content/Input/',
    actions,
  }, null, 2);
}

function buildProjectConfigJson(
  projectName: string,
  scaffold: UnrealScaffoldResult,
  generatedAt: string,
): string {
  const cam      = cameraLabel(scaffold.scaffoldItems);
  const hasSurv  = scaffold.scaffoldItems.some(i => i.category === 'survival');
  const hasInv   = scaffold.scaffoldItems.some(i => i.category === 'inventory');
  const hasEnemy = scaffold.scaffoldItems.some(i => i.category === 'enemy');

  const cameraConfig =
    cam === 'First-Person'
      ? {
          mode: 'first_person',
          componentClass: 'UCameraComponent',
          attachSocket: 'head',
          hideOwnerMesh: true,
        }
      : cam === 'Top-Down'
      ? {
          mode: 'top_down',
          useSpringArm: false,
          fixedPitch: -70,
          fixedDistance: 1200,
          enableEdgeScroll: false,
        }
      : {
          mode: 'third_person',
          springArmLength: 300,
          springArmLagSpeed: 10,
          bUsePawnControlRotation: true,
          cameraLagEnabled: true,
        };

  return JSON.stringify({
    triforgeVersion: '1.0',
    milestone: 'M1',
    project: projectName,
    prototypeGoal: scaffold.prototypeGoal,
    generatedAt,
    instructions: [
      'Create each Blueprint asset listed below in Unreal Editor.',
      'Set BP_GameMode as the default game mode in Project Settings → Maps & Modes.',
      'Set BP_PlayerCharacter as the Default Pawn Class in BP_GameMode.',
      'Create L_TestArena as a new Level and add a Player Start actor.',
      'Add a NavMesh Bounds Volume covering the arena floor for enemy navigation.',
    ],
    assets: {
      gameMode: {
        blueprintName: 'BP_GameMode',
        parentClass: 'GameModeBase',
        contentPath: 'Content/Core/',
        defaultPawnClass: 'BP_PlayerCharacter',
        playerControllerClass: 'BP_PlayerController',
        hud: hasSurv ? 'WBP_HUD' : null,
      },
      gameState: {
        blueprintName: 'BP_GameState',
        parentClass: 'GameStateBase',
        contentPath: 'Content/Core/',
      },
      playerCharacter: {
        blueprintName: 'BP_PlayerCharacter',
        parentClass: 'Character',
        contentPath: 'Content/Player/',
        movementSettings: {
          maxWalkSpeed: 600,
          maxJumpHeight: 420,
          airControl: 0.35,
        },
        cameraMode: cam,
      },
      playerController: {
        blueprintName: 'BP_PlayerController',
        parentClass: 'PlayerController',
        contentPath: 'Content/Player/',
        inputMappingContext: 'IMC_Default',
      },
      camera: cameraConfig,
      testLevel: {
        levelName: 'L_TestArena',
        contentPath: 'Content/Maps/',
        floorSize: '5000x5000',
        includeNavMesh: hasEnemy,
        includePlayerStart: true,
        lightingPreset: 'DefaultSkylight',
      },
    },
    optionalSystems: {
      survivalStats: hasSurv,
      inventoryComponent: hasInv,
      enemyAI: hasEnemy,
    },
  }, null, 2);
}

// ── Main application function ─────────────────────────────────────────────────

/**
 * Apply Milestone 1 to the active Unreal project by generating structured
 * implementation artifacts into <projectRoot>/TriForge/.
 *
 * This is the first real project-facing modification TriForge makes.
 *
 * @param projectPath   Confirmed .uproject path (high-confidence only)
 * @param projectName   Project name derived from .uproject filename
 * @param scaffold      Scaffold result from generateUnrealSystemScaffold()
 * @param milestone     Milestone result from generateUnrealMilestones()
 */
export async function applyUnrealMilestone1(
  projectPath: string,
  projectName: string,
  scaffold: UnrealScaffoldResult,
  milestone: UnrealMilestoneResult,
): Promise<M1ApplicationResult> {
  const projectRoot  = path.dirname(projectPath);
  const triforgeDir  = path.join(projectRoot, 'TriForge');
  const generatedAt  = new Date().toISOString();
  const appliedFiles: M1AppliedFile[] = [];
  const warnings: string[]            = [];
  const errors: string[]              = [];

  // ── 1. Create TriForge directory ──────────────────────────────────────────
  try {
    fs.mkdirSync(triforgeDir, { recursive: true });
  } catch (e: unknown) {
    const msg = e instanceof Error ? e.message : String(e);
    return {
      ok:           false,
      projectRoot,
      triforgeDir,
      appliedFiles: [],
      warnings:     [],
      errors:       [`Failed to create TriForge directory at ${triforgeDir}: ${msg}`],
    };
  }

  // ── 2. Write helper ───────────────────────────────────────────────────────
  function writeFile(
    filename: string,
    content: string,
    description: string,
  ): boolean {
    const absolutePath = path.join(triforgeDir, filename);
    const relativePath = path.join('TriForge', filename);
    try {
      fs.writeFileSync(absolutePath, content, 'utf-8');
      appliedFiles.push({ absolutePath, relativePath, description });
      return true;
    } catch (e: unknown) {
      const msg = e instanceof Error ? e.message : String(e);
      warnings.push(`Could not write ${relativePath}: ${msg}`);
      return false;
    }
  }

  // ── 3. Generate and write all three M1 artifacts ──────────────────────────

  writeFile(
    'M1_Foundation_Setup.md',
    buildSetupMarkdown(projectName, scaffold, milestone, generatedAt),
    'Milestone 1 implementation guide — human-readable steps for game mode, ' +
    'player character, camera, and input setup.',
  );

  writeFile(
    'M1_InputActions.json',
    buildInputActionsJson(projectName, scaffold, generatedAt),
    'Enhanced Input action spec for IMC_Default — action names, value types, ' +
    'trigger types, and suggested key bindings.',
  );

  writeFile(
    'M1_ProjectConfig.json',
    buildProjectConfigJson(projectName, scaffold, generatedAt),
    'Project configuration spec — Blueprint asset list, game mode settings, ' +
    'player character defaults, camera mode, and test level configuration.',
  );

  // Companion Python script — run from Unreal Editor → Tools → Execute Python
  // Script to materialize the M1 assets directly. Idempotent and safe to re-run.
  writeFile(
    'M1_Apply.py',
    buildMilestone1PythonScript(projectName, scaffold, milestone, generatedAt),
    'Companion Python script — runs inside Unreal Editor to create the folder ' +
    'structure, Blueprints, Input Actions, and IMC described above.',
  );

  // ── 4. Write a manifest so future packs can discover what was generated ───
  const manifest = {
    triforgeVersion:  '1.0',
    milestone:        'M1',
    project:          projectName,
    projectPath,
    generatedAt,
    packId:           'pack.unreal-m1-execute',
    files:            appliedFiles.map(f => ({
      relativePath:  f.relativePath,
      description:   f.description,
    })),
  };

  writeFile(
    'M1_Manifest.json',
    JSON.stringify(manifest, null, 2),
    'Machine-readable manifest of all M1 generated files for future pack chaining.',
  );

  // ── 5. B5: Post-write validation ──────────────────────────────────────────
  // Read each written file back from disk and verify structural integrity
  // (parseable JSON, required header fields, milestone tag matches). Files
  // that fail validation are removed from appliedFiles so the pack outcome
  // reflects reality — we cannot honestly report a corrupt file as applied.
  const validation = validateMilestoneBatch(
    appliedFiles.map(f => ({
      absolutePath:      f.absolutePath,
      relativePath:      f.relativePath,
      expectedMilestone: 'M1',
      isManifest:        f.relativePath.endsWith('M1_Manifest.json'),
    })),
  );
  if (validation.failed.length > 0) {
    warnings.push(...validation.warnings);
    const failedPaths = new Set(validation.failed.map(f => f.absolutePath));
    const survivingFiles = appliedFiles.filter(f => !failedPaths.has(f.absolutePath));
    appliedFiles.length = 0;
    appliedFiles.push(...survivingFiles);
  }

  const ok = appliedFiles.length > 0 && errors.length === 0;

  return {
    ok,
    projectRoot,
    triforgeDir,
    appliedFiles,
    warnings,
    errors,
  };
}
