// ── applyUnrealMilestone3.ts — Milestone 3 Project File Generator ─────────────
//
// Phase 4, Step 4B: Third real project modification helper.
//
// Writes Milestone 3 implementation artifacts into <projectRoot>/TriForge/.
// Covers the supporting-systems layer: inventory component, item data definitions,
// and interaction setup. All content adapts to scaffold signals (survival/enemy/
// inventory) detected from the prototype goal and scaffold categories.
//
// TRULY IMPLEMENTED:
//   - M3_SupportingSystems_Setup.md  — human-readable M3 implementation guide
//   - M3_InventoryConfig.json        — inventory component spec (slots/weight/categories)
//   - M3_ItemData.json               — item data definitions (scaffold-adaptive)
//   - M3_InteractionConfig.json      — interaction system config (trace/prompt/component)
//   - M3_Manifest.json               — machine-readable manifest with M2 dependency link
//
// NOT YET:
//   - Blueprint component generation
//   - Editor-native asset mutation
//   - Post-write editor reload

import fs   from 'fs';
import path from 'path';
import type { UnrealScaffoldResult }  from '@triforge/engine';
import type { UnrealMilestoneResult } from '@triforge/engine';

// ── Output types ──────────────────────────────────────────────────────────────

export interface M3AppliedFile {
  absolutePath: string;
  relativePath: string;
  description: string;
}

export interface M3ApplicationResult {
  ok: boolean;
  projectRoot: string;
  triforgeDir: string;
  appliedFiles: M3AppliedFile[];
  warnings: string[];
  errors: string[];
}

// ── Scaffold signal helpers ───────────────────────────────────────────────────

function hasSurvivalItems(scaffold: UnrealScaffoldResult): boolean {
  return scaffold.scaffoldItems.some(i => i.category === 'survival');
}

function hasInventoryItems(scaffold: UnrealScaffoldResult): boolean {
  return scaffold.scaffoldItems.some(i => i.category === 'inventory');
}

function hasEnemyItems(scaffold: UnrealScaffoldResult): boolean {
  return scaffold.scaffoldItems.some(i => i.category === 'enemy');
}

function isSurvivalGoal(scaffold: UnrealScaffoldResult): boolean {
  const lower = scaffold.prototypeGoal.toLowerCase();
  return /survival|survive|hunger|thirst|stamina/.test(lower) || hasSurvivalItems(scaffold);
}

// ── File content builders ─────────────────────────────────────────────────────

function buildSetupMarkdown(
  projectName: string,
  scaffold: UnrealScaffoldResult,
  milestone: UnrealMilestoneResult,
  generatedAt: string,
  m1Present: boolean,
  m2Present: boolean,
): string {
  const m4     = milestone.milestones.find(m => m.id === 'M4');
  const steps  = m4?.steps ?? [];
  const surv   = isSurvivalGoal(scaffold);
  const inv    = hasInventoryItems(scaffold);
  const enemy  = hasEnemyItems(scaffold);

  const stepsMarkdown = steps.length > 0
    ? steps.map((s, i) => `### ${i + 1}. ${s.name}\n${s.description}\n`).join('\n')
    : '> Supporting-systems steps derived from prototype goal.';

  const chainWarnings: string[] = [];
  if (!m1Present) chainWarnings.push('⚠ M1_Manifest.json not found — ensure Milestone 1 (Foundation) was applied before implementing M3.');
  if (!m2Present) chainWarnings.push('⚠ M2_Manifest.json not found — ensure Milestone 2 (Primary Loop / HUD) was applied before implementing M3.');

  return `# TriForge — Milestone 3: Supporting Systems

**Project:** ${projectName}
**Prototype Goal:** ${scaffold.prototypeGoal}
**Inventory System:** ${inv ? 'Yes (scaffold detected)' : 'Minimal (no explicit inventory scaffold)'}
**Survival Items:** ${surv ? 'Yes' : 'No'}
**Enemy/Combat Present:** ${enemy ? 'Yes' : 'No'}
**Generated:** ${generatedAt}
**Generated by:** TriForge pack.unreal-m3-execute (Phase 4, Step 4B)
**Depends on:** M1_Manifest.json (Foundation), M2_Manifest.json (Primary Loop)

${chainWarnings.length > 0 ? `---\n\n## Chain Integrity Warnings\n\n${chainWarnings.join('\n')}\n` : ''}
---

## Milestone Goal

${m4?.goal ?? 'Implement supporting systems: inventory, item data, and interaction so the prototype has a usable economy layer.'}

---

## Implementation Steps

${stepsMarkdown}

---

## Inventory Component (BP_InventoryComponent)

Create an Actor Component Blueprint named **BP_InventoryComponent** in \`Content/Components/\`.

See \`TriForge/M3_InventoryConfig.json\` for the full slot/category spec.

### Required variables

| Variable        | Type             | Default | Notes                                 |
|---------------- |----------------- |-------- |-------------------------------------- |
| MaxSlots        | Integer          | ${inv ? 20 : 10}       | Total inventory slots available        |
| MaxWeightKg     | Float            | ${inv ? 50.0 : 20.0}  | Weight limit; 0 = no weight limit      |
| Items           | Array (ItemData) | []      | Runtime array of held item structs     |

### Required functions

| Name               | Description                                           |
|------------------- |------------------------------------------------------ |
| AddItem(item)      | Add item if slot and weight allow; return bool success |
| RemoveItem(itemId) | Remove item by ID; return removed item or none        |
| HasItem(itemId)    | Check if inventory contains a given item ID           |
| GetWeight()        | Return current total weight of all held items         |

Add **BP_InventoryComponent** to **BP_PlayerCharacter** (from M1).

---

## Item Data Structure (BP_ItemData / DT_Items)

See \`TriForge/M3_ItemData.json\` for the full item definition list.

Recommended approach:
1. Create a **Data Table** (DT_Items) using a struct Row Type that matches the item schema in \`M3_ItemData.json\`.
2. Create a **BP_ItemData** struct Blueprint to define the row type.
3. Reference items in \`BP_InventoryComponent\` via row handles, not hard-coded classes.

---

## Interaction System (BP_InteractionComponent)

Create an Actor Component Blueprint named **BP_InteractionComponent** in \`Content/Components/\`.

See \`TriForge/M3_InteractionConfig.json\` for trace range, prompt text, and class defaults.

### How it works

1. On **Tick** (or on input), cast a line trace forward from the camera by \`TraceRange\` cm.
2. If the hit actor implements **\`BPI_Interactable\`** (an Interface), show the interaction prompt.
3. When the player presses the interact key (IA_Interact from M1), call \`BPI_Interactable::Interact()\` on the target.
4. Implement **\`BPI_Interactable\`** on any actor the player can pick up, open, or activate.

### Implementing item pickup

Any world item (e.g. **BP_WorldItem**) should:
- Implement \`BPI_Interactable\`
- In \`Interact()\`, call \`BP_InventoryComponent::AddItem()\` on the Player Character
- If add succeeds, destroy self; if not, show "Inventory Full" feedback

---

${surv ? `## Survival Item Notes

Since a survival prototype was detected, \`M3_ItemData.json\` includes food and water
consumable types. These items should:

- Restore the **Hunger** or **Thirst** stat (from M2 BP_SurvivalStatsComponent) when used
- Be usable from inventory via a Use action (wire to IA_Interact or a dedicated IA_UseItem)
- Have limited stack counts (e.g. 5 per slot) to create resource scarcity

---

` : ''}${enemy ? `## Loot / Ammo Notes

Since enemy/combat systems are planned (M5), \`M3_ItemData.json\` includes ammo item types.
Reserve inventory category space for ammo now so M5 integration is straightforward.

---

` : ''}## Notes & Assumptions

- BP_InventoryComponent must be added to BP_PlayerCharacter before item pickup works.
- BP_InteractionComponent should be added to BP_PlayerCharacter and driven by IA_Interact (from M1).
- BPI_Interactable should be a Blueprint Interface (not a C++ interface) for easy drag-and-drop implementation.
- Item IDs must be stable strings (e.g. "item.health_pack") — avoid int IDs that shift on reorder.
- Do NOT store item instances directly in saves — store item IDs + quantities for save compatibility.

---

## Next Steps After M3

1. Create DT_Items Data Table with rows matching \`M3_ItemData.json\`.
2. Create BP_InventoryComponent and add to BP_PlayerCharacter.
3. Create BPI_Interactable Blueprint Interface.
4. Create BP_InteractionComponent and add to BP_PlayerCharacter (trace + prompt logic).
5. Create a test world item (BP_WorldItem) that implements BPI_Interactable.
6. Verify item pickup adds to inventory and removes the world item.
7. Run \`pack.unreal-build\` to verify M1+M2+M3 systems compile cleanly.
8. When M3 is stable, proceed to Milestone 4 (${enemy ? 'Enemy / Combat' : 'Progression / Save'} Systems).

---

*This file was generated by TriForge and can be safely edited.*
`;
}

function buildInventoryConfigJson(
  projectName: string,
  scaffold: UnrealScaffoldResult,
  generatedAt: string,
): string {
  const inv   = hasInventoryItems(scaffold);
  const surv  = isSurvivalGoal(scaffold);
  const enemy = hasEnemyItems(scaffold);

  const categories: string[] = ['consumable', 'resource', 'tool'];
  if (inv)   categories.push('weapon', 'armor', 'key_item');
  if (surv)  categories.push('food', 'water');
  if (enemy) categories.push('ammo', 'grenade');

  return JSON.stringify({
    triforgeVersion: '1.0',
    milestone:       'M3',
    project:         projectName,
    prototypeGoal:   scaffold.prototypeGoal,
    generatedAt,
    instructions: [
      'Create BP_InventoryComponent (Actor Component) and add to BP_PlayerCharacter.',
      'Expose MaxSlots and MaxWeightKg as editable instance properties.',
      'Use a Data Table (DT_Items) for item definitions — do not hard-code item classes.',
      'Implement AddItem, RemoveItem, HasItem, GetWeight functions as described in M3_SupportingSystems_Setup.md.',
    ],
    componentBlueprint: {
      name:        'BP_InventoryComponent',
      parentClass: 'ActorComponent',
      contentPath: 'Content/Components/',
    },
    config: {
      maxSlots:    inv ? 20 : 10,
      maxWeightKg: inv ? 50.0 : 20.0,
      weightEnabled: true,
      stackingEnabled: true,
    },
    categories: categories.map(cat => ({
      id:    cat,
      label: cat.replace(/_/g, ' ').replace(/\b\w/g, c => c.toUpperCase()),
      included: true,
    })),
    notes: [
      `Slot count: ${inv ? '20 (inventory scaffold detected)' : '10 (minimal inventory)'}`,
      `Weight limit: ${inv ? '50 kg (inventory scaffold detected)' : '20 kg'}`,
      `Categories: ${categories.join(', ')}`,
    ],
  }, null, 2);
}

function buildItemDataJson(
  projectName: string,
  scaffold: UnrealScaffoldResult,
  generatedAt: string,
): string {
  const surv  = isSurvivalGoal(scaffold);
  const enemy = hasEnemyItems(scaffold);

  type ItemDef = {
    id: string;
    displayName: string;
    description: string;
    category: string;
    weightKg: number;
    maxStackSize: number;
    isConsumable: boolean;
    onUseEffect: string;
    iconPath: string;
    included: boolean;
    reason: string;
  };

  const items: ItemDef[] = [
    {
      id:           'item.health_pack',
      displayName:  'Health Pack',
      description:  'Restores 50 health points when used.',
      category:     'consumable',
      weightKg:     0.3,
      maxStackSize: 5,
      isConsumable: true,
      onUseEffect:  'restore_health:50',
      iconPath:     'Content/UI/Icons/icon_health_pack',
      included:     true,
      reason:       'Always included — core consumable for every prototype.',
    },
    {
      id:           'item.bandage',
      displayName:  'Bandage',
      description:  'Restores 20 health points when used.',
      category:     'consumable',
      weightKg:     0.1,
      maxStackSize: 10,
      isConsumable: true,
      onUseEffect:  'restore_health:20',
      iconPath:     'Content/UI/Icons/icon_bandage',
      included:     true,
      reason:       'Always included — lightweight consumable for early-game use.',
    },
    {
      id:           'item.wood',
      displayName:  'Wood',
      description:  'A bundle of raw wood. Used in crafting.',
      category:     'resource',
      weightKg:     1.0,
      maxStackSize: 20,
      isConsumable: false,
      onUseEffect:  'none',
      iconPath:     'Content/UI/Icons/icon_wood',
      included:     true,
      reason:       'Always included — basic resource for crafting and building.',
    },
    {
      id:           'item.stone',
      displayName:  'Stone',
      description:  'A chunk of raw stone. Used in crafting.',
      category:     'resource',
      weightKg:     2.0,
      maxStackSize: 20,
      isConsumable: false,
      onUseEffect:  'none',
      iconPath:     'Content/UI/Icons/icon_stone',
      included:     true,
      reason:       'Always included — basic resource for crafting.',
    },
    {
      id:           'item.flashlight',
      displayName:  'Flashlight',
      description:  'A handheld light source.',
      category:     'tool',
      weightKg:     0.5,
      maxStackSize: 1,
      isConsumable: false,
      onUseEffect:  'toggle_light',
      iconPath:     'Content/UI/Icons/icon_flashlight',
      included:     true,
      reason:       'Always included — useful tool for exploring environments.',
    },
    {
      id:           'item.food_ration',
      displayName:  'Food Ration',
      description:  'Restores 30 hunger when consumed.',
      category:     'food',
      weightKg:     0.4,
      maxStackSize: 5,
      isConsumable: true,
      onUseEffect:  'restore_hunger:30',
      iconPath:     'Content/UI/Icons/icon_food_ration',
      included:     surv,
      reason:       surv
        ? 'Included — survival prototype detected from goal/scaffold.'
        : 'Excluded — prototype goal does not indicate a survival loop.',
    },
    {
      id:           'item.water_bottle',
      displayName:  'Water Bottle',
      description:  'Restores 40 thirst when consumed.',
      category:     'water',
      weightKg:     0.5,
      maxStackSize: 3,
      isConsumable: true,
      onUseEffect:  'restore_thirst:40',
      iconPath:     'Content/UI/Icons/icon_water_bottle',
      included:     surv,
      reason:       surv
        ? 'Included — survival prototype detected from goal/scaffold.'
        : 'Excluded — prototype goal does not indicate a survival loop.',
    },
    {
      id:           'item.ammo_pistol',
      displayName:  'Pistol Ammo',
      description:  '9mm pistol rounds. 15 per stack.',
      category:     'ammo',
      weightKg:     0.2,
      maxStackSize: 60,
      isConsumable: true,
      onUseEffect:  'load_weapon:pistol',
      iconPath:     'Content/UI/Icons/icon_ammo_pistol',
      included:     enemy,
      reason:       enemy
        ? 'Included — enemy/combat systems detected in scaffold.'
        : 'Excluded — no enemy or combat systems detected.',
    },
    {
      id:           'item.ammo_rifle',
      displayName:  'Rifle Ammo',
      description:  '5.56mm rifle rounds. 30 per stack.',
      category:     'ammo',
      weightKg:     0.4,
      maxStackSize: 90,
      isConsumable: true,
      onUseEffect:  'load_weapon:rifle',
      iconPath:     'Content/UI/Icons/icon_ammo_rifle',
      included:     enemy,
      reason:       enemy
        ? 'Included — enemy/combat systems detected in scaffold.'
        : 'Excluded — no enemy or combat systems detected.',
    },
  ];

  return JSON.stringify({
    triforgeVersion: '1.0',
    milestone:       'M3',
    project:         projectName,
    prototypeGoal:   scaffold.prototypeGoal,
    generatedAt,
    instructions: [
      'Create a Struct Blueprint (S_ItemData) with fields matching each item definition below.',
      'Create a Data Table (DT_Items) using S_ItemData as the Row Type.',
      'Add each included item below as a row in DT_Items.',
      'Reference items by RowName (the item id) when adding to inventory.',
      'Excluded items are listed with their reason — include them if the prototype goal changes.',
    ],
    dataTableBlueprint: {
      name:        'DT_Items',
      rowType:     'S_ItemData',
      contentPath: 'Content/Data/',
    },
    items: items.filter(i => i.included),
    excludedItems: items.filter(i => !i.included).map(i => ({ id: i.id, reason: i.reason })),
  }, null, 2);
}

function buildInteractionConfigJson(
  projectName: string,
  scaffold: UnrealScaffoldResult,
  generatedAt: string,
): string {
  const enemy = hasEnemyItems(scaffold);

  return JSON.stringify({
    triforgeVersion: '1.0',
    milestone:       'M3',
    project:         projectName,
    prototypeGoal:   scaffold.prototypeGoal,
    generatedAt,
    instructions: [
      'Create BP_InteractionComponent (Actor Component) and add to BP_PlayerCharacter.',
      'Create BPI_Interactable (Blueprint Interface) with a single Interact() function.',
      'In BP_InteractionComponent Tick (or on IA_Interact press), cast a line trace using traceRangecm.',
      'If the hit actor implements BPI_Interactable, show the promptText UI element.',
      'On IA_Interact press, call BPI_Interactable::Interact() on the focused actor.',
      'Implement BPI_Interactable on any world actor that the player can interact with.',
    ],
    componentBlueprint: {
      name:        'BP_InteractionComponent',
      parentClass: 'ActorComponent',
      contentPath: 'Content/Components/',
    },
    interfaceBlueprint: {
      name:        'BPI_Interactable',
      functions:   [
        {
          name:        'Interact',
          description: 'Called when the player interacts with this actor.',
          params:      [{ name: 'Instigator', type: 'APlayerCharacter*' }],
        },
      ],
      contentPath: 'Content/Interfaces/',
    },
    traceRangeCm:      250,
    traceChannel:      'Visibility',
    promptText:        '[E] to interact',
    promptWidget:      'WBP_InteractionPrompt',
    promptContentPath: 'Content/UI/',
    pickupTypes: [
      {
        id:          'world_item',
        description: 'A world-placed item that adds itself to inventory on interact.',
        blueprint:   'BP_WorldItem',
        contentPath: 'Content/Items/',
        onInteract:  'BP_InventoryComponent::AddItem → if success, destroy self',
      },
      ...(enemy ? [{
        id:          'loot_container',
        description: 'A container (chest, crate) that spawns loot items on interact.',
        blueprint:   'BP_LootContainer',
        contentPath: 'Content/Items/',
        onInteract:  'Roll loot table, spawn BP_WorldItem for each result',
      }] : []),
    ],
    notes: [
      'BPI_Interactable should be a Blueprint Interface — not a C++ interface — for ease of use.',
      'Show interaction prompt only when a valid interactable is in range and line-of-sight.',
      `Trace range: ${250} cm (~2.5 m) — adjust per prototype feel.`,
    ],
  }, null, 2);
}

// ── Main application function ─────────────────────────────────────────────────

/**
 * Apply Milestone 3 to the active Unreal project by generating structured
 * supporting-systems artifacts into <projectRoot>/TriForge/.
 *
 * @param projectPath      Confirmed .uproject path (high-confidence)
 * @param projectName      Project name
 * @param scaffold         Scaffold result from generateUnrealSystemScaffold()
 * @param milestone        Milestone result from generateUnrealMilestones()
 * @param m1ManifestExists Whether M1_Manifest.json is present (chain signal)
 * @param m2ManifestExists Whether M2_Manifest.json is present (chain signal)
 */
export async function applyUnrealMilestone3(
  projectPath: string,
  projectName: string,
  scaffold: UnrealScaffoldResult,
  milestone: UnrealMilestoneResult,
  m1ManifestExists: boolean,
  m2ManifestExists: boolean,
): Promise<M3ApplicationResult> {
  const projectRoot = path.dirname(projectPath);
  const triforgeDir = path.join(projectRoot, 'TriForge');
  const generatedAt = new Date().toISOString();
  const appliedFiles: M3AppliedFile[] = [];
  const warnings: string[]            = [];
  const errors: string[]              = [];

  if (!m1ManifestExists) {
    warnings.push(
      'M1_Manifest.json was not found in TriForge/ — Milestone 1 (Foundation) may not have been applied yet. ' +
      'M3 artifacts are still written, but review the M1 foundation before implementing M3.',
    );
  }

  if (!m2ManifestExists) {
    warnings.push(
      'M2_Manifest.json was not found in TriForge/ — Milestone 2 (Primary Loop / HUD) may not have been applied yet. ' +
      'M3 artifacts are still written, but review the M2 systems before implementing M3.',
    );
  }

  // ── Ensure TriForge directory exists ─────────────────────────────────────
  try {
    fs.mkdirSync(triforgeDir, { recursive: true });
  } catch (e: unknown) {
    const msg = e instanceof Error ? e.message : String(e);
    return {
      ok: false, projectRoot, triforgeDir,
      appliedFiles: [], warnings,
      errors: [`Failed to create TriForge directory at ${triforgeDir}: ${msg}`],
    };
  }

  // ── Write helper ──────────────────────────────────────────────────────────
  function writeFile(filename: string, content: string, description: string): boolean {
    const absolutePath = path.join(triforgeDir, filename);
    const relativePath = path.join('TriForge', filename);
    try {
      fs.writeFileSync(absolutePath, content, 'utf-8');
      appliedFiles.push({ absolutePath, relativePath, description });
      return true;
    } catch (e: unknown) {
      const msg = e instanceof Error ? e.message : String(e);
      warnings.push(`Could not write ${relativePath}: ${msg}`);
      return false;
    }
  }

  // ── Write M3 artifacts ────────────────────────────────────────────────────
  writeFile(
    'M3_SupportingSystems_Setup.md',
    buildSetupMarkdown(projectName, scaffold, milestone, generatedAt, m1ManifestExists, m2ManifestExists),
    'Milestone 3 implementation guide — inventory component, item data, and interaction system setup.',
  );

  writeFile(
    'M3_InventoryConfig.json',
    buildInventoryConfigJson(projectName, scaffold, generatedAt),
    'Inventory component spec — slot count, weight limit, and item categories (scaffold-adaptive).',
  );

  writeFile(
    'M3_ItemData.json',
    buildItemDataJson(projectName, scaffold, generatedAt),
    'Item data definitions — base items always present; survival/ammo items when scaffold signals detected.',
  );

  writeFile(
    'M3_InteractionConfig.json',
    buildInteractionConfigJson(projectName, scaffold, generatedAt),
    'Interaction system config — trace range, prompt text, BPI_Interactable interface, and pickup types.',
  );

  // ── Manifest ──────────────────────────────────────────────────────────────
  const chainIntegrityNotes: string[] = [];
  if (!m1ManifestExists) chainIntegrityNotes.push('M1_Manifest.json missing — M1 foundation may not be applied.');
  if (!m2ManifestExists) chainIntegrityNotes.push('M2_Manifest.json missing — M2 primary loop may not be applied.');

  const dependsOn: string[] = [];
  if (m2ManifestExists) dependsOn.push('M2_Manifest.json');
  if (m1ManifestExists && !m2ManifestExists) dependsOn.push('M1_Manifest.json');

  const manifest = {
    triforgeVersion: '1.0',
    milestone:       'M3',
    project:         projectName,
    projectPath,
    generatedAt,
    packId:          'pack.unreal-m3-execute',
    dependsOn,
    files: appliedFiles.map(f => ({ relativePath: f.relativePath, description: f.description })),
    notes: [
      `Inventory: ${hasInventoryItems(scaffold) ? 'full inventory scaffold (20 slots, 50 kg limit)' : 'minimal inventory (10 slots, 20 kg limit)'}`,
      `Item types: ${isSurvivalGoal(scaffold) ? 'includes survival consumables (food/water)' : 'base items only (no survival consumables)'}`,
      `Ammo items: ${hasEnemyItems(scaffold) ? 'included (enemy/combat scaffold detected)' : 'not included'}`,
      ...chainIntegrityNotes,
    ],
    recommendedNext: 'pack.unreal-m4-execute',
  };

  writeFile(
    'M3_Manifest.json',
    JSON.stringify(manifest, null, 2),
    'Machine-readable manifest of all M3 generated files for future pack chaining.',
  );

  const ok = appliedFiles.length > 0 && errors.length === 0;
  return { ok, projectRoot, triforgeDir, appliedFiles, warnings, errors };
}
