// ── applyUnrealMilestone2.ts — Milestone 2 Project File Generator ─────────────
//
// Phase 4, Step 2: Second real project modification helper.
//
// Writes Milestone 2 implementation artifacts into <projectRoot>/TriForge/.
// Covers the primary gameplay loop layer: health/survival stats, HUD config,
// and primary loop setup instructions.
//
// TRULY IMPLEMENTED:
//   - M2_PrimaryLoop_Setup.md  — human-readable M2 implementation guide
//   - M2_SurvivalStats.json    — structured stat component definition
//   - M2_HUDConfig.json        — HUD widget spec and stat binding config
//   - M2_Manifest.json         — machine-readable manifest with M1 dependency link
//
// NOT YET:
//   - Blueprint component generation
//   - Widget Blueprint creation
//   - Editor-side UMG layout writing
//   - Post-write editor reload

import fs   from 'fs';
import path from 'path';
import type { UnrealScaffoldResult }  from '@triforge/engine';
import type { UnrealMilestoneResult } from '@triforge/engine';
import { validateMilestoneBatch }     from './unrealMilestoneValidator';
import { buildMilestone2PythonScript } from './unrealMilestonePython';

// ── Output types ──────────────────────────────────────────────────────────────

export interface M2AppliedFile {
  absolutePath: string;
  relativePath: string;
  description: string;
}

export interface M2ApplicationResult {
  ok: boolean;
  projectRoot: string;
  triforgeDir: string;
  appliedFiles: M2AppliedFile[];
  warnings: string[];
  errors: string[];
}

// ── Scaffold signal helpers ───────────────────────────────────────────────────

function hasSurvivalItems(scaffold: UnrealScaffoldResult): boolean {
  return scaffold.scaffoldItems.some(i => i.category === 'survival');
}

function hasInventoryItems(scaffold: UnrealScaffoldResult): boolean {
  return scaffold.scaffoldItems.some(i => i.category === 'inventory');
}

function hasEnemyItems(scaffold: UnrealScaffoldResult): boolean {
  return scaffold.scaffoldItems.some(i => i.category === 'enemy');
}

function isSurvivalGoal(scaffold: UnrealScaffoldResult): boolean {
  const lower = scaffold.prototypeGoal.toLowerCase();
  return /survival|survive|hunger|thirst|stamina/.test(lower) || hasSurvivalItems(scaffold);
}

// ── File content builders ─────────────────────────────────────────────────────

function buildSetupMarkdown(
  projectName: string,
  scaffold: UnrealScaffoldResult,
  milestone: UnrealMilestoneResult,
  generatedAt: string,
): string {
  const m3     = milestone.milestones.find(m => m.id === 'M3');
  const steps  = m3?.steps ?? [];
  const surv   = isSurvivalGoal(scaffold);
  const inv    = hasInventoryItems(scaffold);
  const enemy  = hasEnemyItems(scaffold);

  const stepsMarkdown = steps.length > 0
    ? steps.map((s, i) => `### ${i + 1}. ${s.name}\n${s.description}\n`).join('\n')
    : '> Stat system steps derived from prototype goal.';

  return `# TriForge — Milestone 2: Primary Loop / Health / HUD

**Project:** ${projectName}
**Prototype Goal:** ${scaffold.prototypeGoal}
**Survival Mode:** ${surv ? 'Yes' : 'No'}
**Generated:** ${generatedAt}
**Generated by:** TriForge pack.unreal-m2-execute (Phase 4, Step 2)
**Depends on:** M1_Manifest.json (Foundation must be complete)

---

## Milestone Goal

${m3?.goal ?? 'Implement the primary health/survival stat loop with HUD feedback.'}

---

## Implementation Steps

${stepsMarkdown}

---

## Health Component (BP_HealthComponent)

Create an Actor Component Blueprint named **BP_HealthComponent** in \`Content/Components/\`.

### Required variables

| Variable        | Type    | Default | Notes                         |
|---------------- |-------- |-------- |------------------------------ |
| MaxHealth       | Float   | 100.0   | Maximum health value          |
| CurrentHealth   | Float   | 100.0   | Runtime health (init = Max)   |
| bIsDead         | Boolean | false   | Set true when Health ≤ 0      |

### Required events / functions

| Name             | Description                                        |
|----------------- |--------------------------------------------------- |
| TakeDamage(amt)  | Reduce CurrentHealth by amt; call Die() at 0       |
| Heal(amt)        | Increase CurrentHealth, clamp to MaxHealth         |
| Die()            | Set bIsDead, fire OnDeath delegate                 |
| OnHealthChanged  | Event dispatcher — bound by HUD to update display  |

Add **BP_HealthComponent** to **BP_PlayerCharacter** (from M1).

---

${surv ? `## Survival Stats (BP_SurvivalStatsComponent)

See \`TriForge/M2_SurvivalStats.json\` for the full stat spec.

Create **BP_SurvivalStatsComponent** in \`Content/Components/\` with the
stat definitions from the JSON file. Wire each stat's OnChanged dispatcher
to the HUD widget for live display.

### Decay timers

| Stat     | Default Decay Rate | Critical Threshold | Effect at Critical   |
|--------- |------------------ |------------------ |--------------------- |
| Stamina  | 5.0 / sec (sprint)| 10%               | Speed penalty        |
| Hunger   | 0.5 / sec          | 10%               | Health drain trigger |
| Thirst   | 0.8 / sec          | 10%               | Health drain trigger |

Decay should only tick when the player is alive (\`bIsDead == false\`).

---

` : ''}## HUD Widget (WBP_HUD)

See \`TriForge/M2_HUDConfig.json\` for the full widget spec.

Create **WBP_HUD** in \`Content/UI/\` using the Canvas Panel layout defined
in the config file.

### Minimum required UI elements

| Element            | Bound to              | Position (anchored)    |
|------------------- |---------------------- |----------------------- |
| HealthBar (Progress)| BP_HealthComponent   | Top-left, offset 20,20 |
${surv ? `| StaminaBar (Progress)| BP_SurvivalStats    | Top-left, below health |
| HungerIcon + value | BP_SurvivalStats      | Bottom-left            |
| ThirstIcon + value | BP_SurvivalStats      | Bottom-left, right     |
` : ''}\

### Binding WBP_HUD

1. In **BP_PlayerController** (from M1) BeginPlay:
   \`\`\`
   CreateWidget(WBP_HUD) → Add to Viewport (Z-order 0)
   \`\`\`
2. Pass the Player Character reference to the HUD widget after creation.
3. In WBP_HUD, bind the progress bar percent to a function that reads
   \`CurrentHealth / MaxHealth\` from BP_HealthComponent.

---

${enemy ? `## Damage Feedback

Since enemies are planned for Milestone 5, add a damage flash effect
to WBP_HUD now so it is ready when enemies arrive:

- Full-screen red tint image (alpha 0 by default)
- Triggered by BP_HealthComponent → OnHealthChanged with delta < 0
- Quick fade-in then fade-out animation (0.1 sec in, 0.4 sec out)

This does NOT require enemies to be implemented yet.

---

` : ''}## Notes & Assumptions

- BP_HealthComponent must be attached to BP_PlayerCharacter before binding WBP_HUD.
- If stamina exists, sprint input should reduce stamina and clamp speed at 0 stamina.
${inv ? '- Inventory UI (from M4) will share the same HUD canvas — reserve layout space.\n' : ''}\
- WBP_HUD should be created and managed by BP_PlayerController, not BP_Character.
- Do NOT use the deprecated UGameplayStatics::GetPlayerHUD path — use widgets directly.

---

## Next Steps After M2

1. Attach BP_HealthComponent to BP_PlayerCharacter.
${surv ? '2. Attach BP_SurvivalStatsComponent to BP_PlayerCharacter.\n' : ''}\
${surv ? '3' : '2'}. Create WBP_HUD and add it to the viewport in BP_PlayerController.
${surv ? '4' : '3'}. Verify health display updates when test-damage is applied (e.g. from a debug key).
${surv ? '5' : '4'}. Run \`pack.unreal-build\` to verify M1+M2 systems compile cleanly.
${surv ? '6' : '5'}. When M2 is stable, proceed to Milestone 3 (Supporting Systems).

---

*This file was generated by TriForge and can be safely edited.*
`;
}

function buildSurvivalStatsJson(
  projectName: string,
  scaffold: UnrealScaffoldResult,
  generatedAt: string,
): string {
  const surv = isSurvivalGoal(scaffold);

  // Always include health. Survival extras only when justified.
  const stats: Array<{
    id: string;
    displayName: string;
    defaultValue: number;
    minValue: number;
    maxValue: number;
    decayPerSecond: number;
    criticalThreshold: number;
    criticalEffect: string;
    uiBarColor: string;
    included: boolean;
    reason: string;
  }> = [
    {
      id:                'health',
      displayName:       'Health',
      defaultValue:      100,
      minValue:          0,
      maxValue:          100,
      decayPerSecond:    0,
      criticalThreshold: 20,
      criticalEffect:    'trigger_death_at_zero',
      uiBarColor:        '#CC3333',
      included:          true,
      reason:            'Always included — core of every prototype.',
    },
    {
      id:                'stamina',
      displayName:       'Stamina',
      defaultValue:      100,
      minValue:          0,
      maxValue:          100,
      decayPerSecond:    5.0,
      criticalThreshold: 10,
      criticalEffect:    'prevent_sprint',
      uiBarColor:        '#33AACC',
      included:          true,
      reason:            'Always included — used by player movement (sprint).',
    },
    {
      id:                'hunger',
      displayName:       'Hunger',
      defaultValue:      100,
      minValue:          0,
      maxValue:          100,
      decayPerSecond:    0.5,
      criticalThreshold: 10,
      criticalEffect:    'drain_health_at_0.2_per_sec',
      uiBarColor:        '#CCAA33',
      included:          surv,
      reason:            surv
        ? 'Included — survival prototype detected from goal/scaffold.'
        : 'Excluded — prototype goal does not indicate a survival loop.',
    },
    {
      id:                'thirst',
      displayName:       'Thirst',
      defaultValue:      100,
      minValue:          0,
      maxValue:          100,
      decayPerSecond:    0.8,
      criticalThreshold: 10,
      criticalEffect:    'drain_health_at_0.3_per_sec',
      uiBarColor:        '#3399CC',
      included:          surv,
      reason:            surv
        ? 'Included — survival prototype detected from goal/scaffold.'
        : 'Excluded — prototype goal does not indicate a survival loop.',
    },
  ];

  return JSON.stringify({
    triforgeVersion: '1.0',
    milestone:       'M2',
    project:         projectName,
    prototypeGoal:   scaffold.prototypeGoal,
    generatedAt,
    instructions: [
      'Create BP_HealthComponent (Actor Component) for health and add it to BP_PlayerCharacter.',
      surv
        ? 'Create BP_SurvivalStatsComponent (Actor Component) for stamina/hunger/thirst and add to BP_PlayerCharacter.'
        : 'Create a BP_StaminaComponent for stamina only (no full survival loop detected).',
      'Wire each stat\'s OnChanged event dispatcher to WBP_HUD for live display.',
      'Set decay timers to tick only when bIsDead == false.',
    ],
    componentBlueprints: [
      { name: 'BP_HealthComponent',       parentClass: 'ActorComponent', contentPath: 'Content/Components/' },
      surv
        ? { name: 'BP_SurvivalStatsComponent', parentClass: 'ActorComponent', contentPath: 'Content/Components/' }
        : { name: 'BP_StaminaComponent',        parentClass: 'ActorComponent', contentPath: 'Content/Components/' },
    ],
    stats: stats.filter(s => s.included),
    excludedStats: stats.filter(s => !s.included).map(s => ({ id: s.id, reason: s.reason })),
  }, null, 2);
}

function buildHUDConfigJson(
  projectName: string,
  scaffold: UnrealScaffoldResult,
  generatedAt: string,
): string {
  const surv  = isSurvivalGoal(scaffold);
  const inv   = hasInventoryItems(scaffold);
  const enemy = hasEnemyItems(scaffold);

  const widgets: Array<{
    id: string;
    widgetType: string;
    boundStat: string;
    anchor: string;
    offsetX: number;
    offsetY: number;
    width: number;
    height: number;
    barColor?: string;
    notes: string;
  }> = [
    {
      id: 'health_bar',
      widgetType: 'UProgressBar',
      boundStat: 'health',
      anchor: 'top_left',
      offsetX: 20, offsetY: 20,
      width: 200, height: 20,
      barColor: '#CC3333',
      notes: 'Percent = CurrentHealth / MaxHealth from BP_HealthComponent.',
    },
    {
      id: 'stamina_bar',
      widgetType: 'UProgressBar',
      boundStat: 'stamina',
      anchor: 'top_left',
      offsetX: 20, offsetY: 50,
      width: 200, height: 14,
      barColor: '#33AACC',
      notes: 'Percent = CurrentStamina / MaxStamina. Hide when stamina == max.',
    },
  ];

  if (surv) {
    widgets.push(
      {
        id: 'hunger_value',
        widgetType: 'UTextBlock',
        boundStat: 'hunger',
        anchor: 'bottom_left',
        offsetX: 20, offsetY: -60,
        width: 80, height: 24,
        notes: 'Show integer percent. Red text when < criticalThreshold.',
      },
      {
        id: 'thirst_value',
        widgetType: 'UTextBlock',
        boundStat: 'thirst',
        anchor: 'bottom_left',
        offsetX: 110, offsetY: -60,
        width: 80, height: 24,
        notes: 'Show integer percent. Red text when < criticalThreshold.',
      },
    );
  }

  if (enemy) {
    widgets.push({
      id: 'damage_flash',
      widgetType: 'UImage',
      boundStat: 'health_delta',
      anchor: 'full_screen',
      offsetX: 0, offsetY: 0,
      width: 0, height: 0,
      barColor: '#CC000066',
      notes: 'Full-screen red tint. Alpha 0 by default. Play FadeIn+FadeOut anim on damage.',
    });
  }

  return JSON.stringify({
    triforgeVersion: '1.0',
    milestone:       'M2',
    project:         projectName,
    prototypeGoal:   scaffold.prototypeGoal,
    generatedAt,
    instructions: [
      'Create WBP_HUD (User Widget Blueprint) in Content/UI/.',
      'Add a Canvas Panel as the root widget.',
      'Add each element below to the Canvas Panel at the specified anchor/offset.',
      'In BP_PlayerController BeginPlay, create WBP_HUD and call AddToViewport (Z=0).',
      'Pass the Player Character reference to WBP_HUD after creation.',
    ],
    widgetBlueprint: {
      name:        'WBP_HUD',
      parentClass: 'UserWidget',
      contentPath: 'Content/UI/',
    },
    layout: {
      rootWidget: 'Canvas Panel',
      designResolution: { width: 1920, height: 1080 },
      elements: widgets,
    },
    futureReservations: [
      inv   ? 'Reserve bottom-right quadrant for inventory toggle button (M4).' : null,
      enemy ? 'Damage flash overlay slot already included (activated in M5).' : null,
    ].filter(Boolean),
  }, null, 2);
}

// ── Main application function ─────────────────────────────────────────────────

/**
 * Apply Milestone 2 to the active Unreal project by generating structured
 * implementation artifacts into <projectRoot>/TriForge/.
 *
 * @param projectPath  Confirmed .uproject path (high-confidence)
 * @param projectName  Project name
 * @param scaffold     Scaffold result from generateUnrealSystemScaffold()
 * @param milestone    Milestone result from generateUnrealMilestones()
 * @param m1ManifestExists Whether M1_Manifest.json is already present (chain signal)
 */
export async function applyUnrealMilestone2(
  projectPath: string,
  projectName: string,
  scaffold: UnrealScaffoldResult,
  milestone: UnrealMilestoneResult,
  m1ManifestExists: boolean,
): Promise<M2ApplicationResult> {
  const projectRoot = path.dirname(projectPath);
  const triforgeDir = path.join(projectRoot, 'TriForge');
  const generatedAt = new Date().toISOString();
  const appliedFiles: M2AppliedFile[] = [];
  const warnings: string[]            = [];
  const errors: string[]              = [];

  if (!m1ManifestExists) {
    warnings.push(
      'M1_Manifest.json was not found in TriForge/ — Milestone 1 may not have been applied yet. ' +
      'M2 artifacts are still written, but review the M1 foundation before implementing M2.',
    );
  }

  // ── Ensure TriForge directory exists ─────────────────────────────────────
  try {
    fs.mkdirSync(triforgeDir, { recursive: true });
  } catch (e: unknown) {
    const msg = e instanceof Error ? e.message : String(e);
    return {
      ok: false, projectRoot, triforgeDir,
      appliedFiles: [], warnings,
      errors: [`Failed to create TriForge directory at ${triforgeDir}: ${msg}`],
    };
  }

  // ── Write helper ──────────────────────────────────────────────────────────
  function writeFile(filename: string, content: string, description: string): boolean {
    const absolutePath = path.join(triforgeDir, filename);
    const relativePath = path.join('TriForge', filename);
    try {
      fs.writeFileSync(absolutePath, content, 'utf-8');
      appliedFiles.push({ absolutePath, relativePath, description });
      return true;
    } catch (e: unknown) {
      const msg = e instanceof Error ? e.message : String(e);
      warnings.push(`Could not write ${relativePath}: ${msg}`);
      return false;
    }
  }

  // ── Write M2 artifacts ────────────────────────────────────────────────────
  writeFile(
    'M2_PrimaryLoop_Setup.md',
    buildSetupMarkdown(projectName, scaffold, milestone, generatedAt),
    'Milestone 2 implementation guide — health component, survival stats, and HUD setup.',
  );

  writeFile(
    'M2_SurvivalStats.json',
    buildSurvivalStatsJson(projectName, scaffold, generatedAt),
    'Survival stat component spec — health/stamina always present; hunger/thirst when survival prototype detected.',
  );

  writeFile(
    'M2_HUDConfig.json',
    buildHUDConfigJson(projectName, scaffold, generatedAt),
    'HUD widget spec — canvas layout, stat bindings, anchors, and future reservation slots.',
  );

  // ── Manifest ──────────────────────────────────────────────────────────────
  const manifest = {
    triforgeVersion: '1.0',
    milestone:       'M2',
    project:         projectName,
    projectPath,
    generatedAt,
    packId:          'pack.unreal-m2-execute',
    dependsOn:       m1ManifestExists ? ['M1_Manifest.json'] : [],
    notes: [
      `Survival stats: ${isSurvivalGoal(scaffold) ? 'health + stamina + hunger + thirst' : 'health + stamina only'}`,
      `HUD enemy damage flash: ${hasEnemyItems(scaffold) ? 'included (activated in M5)' : 'not included'}`,
      `Inventory HUD reservation: ${hasInventoryItems(scaffold) ? 'yes (M4)' : 'no'}`,
    ],
    files: appliedFiles.map(f => ({ relativePath: f.relativePath, description: f.description })),
  };

  writeFile(
    'M2_Manifest.json',
    JSON.stringify(manifest, null, 2),
    'Machine-readable manifest of all M2 generated files for future pack chaining.',
  );

  // Companion Python script — run from Unreal Editor → Tools → Execute Python
  // Script to materialize the M2 health/HUD assets directly. Idempotent.
  writeFile(
    'M2_Apply.py',
    buildMilestone2PythonScript(projectName, scaffold, milestone, generatedAt),
    'Companion Python script — runs inside Unreal Editor to create the health, ' +
    'HUD widget, and survival component scaffolds described above.',
  );

  // ── B5: Post-write validation ──────────────────────────────────────────
  const validation = validateMilestoneBatch(
    appliedFiles.map(f => ({
      absolutePath:      f.absolutePath,
      relativePath:      f.relativePath,
      expectedMilestone: 'M2',
      isManifest:        f.relativePath.endsWith('M2_Manifest.json'),
    })),
  );
  if (validation.failed.length > 0) {
    warnings.push(...validation.warnings);
    const failedPaths = new Set(validation.failed.map(f => f.absolutePath));
    const survivingFiles = appliedFiles.filter(f => !failedPaths.has(f.absolutePath));
    appliedFiles.length = 0;
    appliedFiles.push(...survivingFiles);
  }

  const ok = appliedFiles.length > 0 && errors.length === 0;
  return { ok, projectRoot, triforgeDir, appliedFiles, warnings, errors };
}
