// ── applyUnrealMilestone5.ts — Milestone 5 Project File Generator ─────────────
//
// Phase 4, Step 6: Fifth real project modification helper.
//
// Writes Milestone 5 implementation artifacts into <projectRoot>/TriForge/.
// Covers the progression and save-system layer: save game spec, unlock/XP config,
// and checkpoint placement. Content adapts to scaffold signals (survival/enemy/
// inventory) detected from the prototype goal and scaffold categories.
//
// TRULY IMPLEMENTED:
//   - M5_Progression_Setup.md   — human-readable M5 implementation guide
//   - M5_SaveGameConfig.json     — save game spec (what/when/how to save)
//   - M5_ProgressionConfig.json  — unlock/level/XP progression spec
//   - M5_CheckpointConfig.json   — checkpoint placement and respawn config
//   - M5_Manifest.json           — machine-readable manifest with M4 dependency link
//
// NEXT STEPS (done by developer in Unreal Editor):
//   - Create BP_SaveGame with fields from M5_SaveGameConfig.json
//   - Implement save/load in BP_GameMode using the spec
//   - Place checkpoint volumes from M5_CheckpointConfig.json in the test level

import fs   from 'fs';
import path from 'path';
import type { UnrealScaffoldResult }  from '@triforge/engine';
import type { UnrealMilestoneResult } from '@triforge/engine';
import { validateMilestoneBatch }     from './unrealMilestoneValidator';
import { buildMilestone5PythonScript } from './unrealMilestonePython';

// ── Output types ──────────────────────────────────────────────────────────────

export interface M5AppliedFile {
  absolutePath: string;
  relativePath: string;
  description: string;
}

export interface M5ApplicationResult {
  ok: boolean;
  projectRoot: string;
  triforgeDir: string;
  appliedFiles: M5AppliedFile[];
  warnings: string[];
  errors: string[];
}

// ── Scaffold signal helpers ───────────────────────────────────────────────────

function hasEnemyItems(scaffold: UnrealScaffoldResult): boolean {
  return scaffold.scaffoldItems.some(i => i.category === 'enemy');
}

function hasSurvivalItems(scaffold: UnrealScaffoldResult): boolean {
  return scaffold.scaffoldItems.some(i => i.category === 'survival');
}

function hasInventoryItems(scaffold: UnrealScaffoldResult): boolean {
  return scaffold.scaffoldItems.some(i => i.category === 'inventory');
}

function isSurvivalGoal(scaffold: UnrealScaffoldResult): boolean {
  const lower = scaffold.prototypeGoal.toLowerCase();
  return /survival|survive|hunger|thirst|zombie|infected|creature/.test(lower) || hasSurvivalItems(scaffold);
}

// ── File content builders ─────────────────────────────────────────────────────

function buildSetupMarkdown(
  projectName: string,
  scaffold: UnrealScaffoldResult,
  milestone: UnrealMilestoneResult,
  generatedAt: string,
  m1Present: boolean,
  m2Present: boolean,
  m3Present: boolean,
  m4Present: boolean,
): string {
  const m6     = milestone.milestones.find(m => m.id === 'M6');
  const steps  = m6?.steps ?? [];
  const surv   = isSurvivalGoal(scaffold);
  const inv    = hasInventoryItems(scaffold);
  const enemy  = hasEnemyItems(scaffold);

  const stepsMarkdown = steps.length > 0
    ? steps.map((s, i) => `### ${i + 1}. ${s.name}\n${s.description}\n`).join('\n')
    : '> Progression/save implementation steps derived from prototype goal.';

  const chainWarnings: string[] = [];
  if (!m1Present) chainWarnings.push('⚠ M1_Manifest.json not found — M1 (Foundation) may not be applied.');
  if (!m2Present) chainWarnings.push('⚠ M2_Manifest.json not found — M2 (Primary Loop / HUD) may not be applied.');
  if (!m3Present) chainWarnings.push('⚠ M3_Manifest.json not found — M3 (Supporting Systems) may not be applied.');
  if (!m4Present) chainWarnings.push('⚠ M4_Manifest.json not found — M4 (Enemy / Combat) may not be applied. Save data will include kill/score fields but they have no source until M4 is wired.');

  return `# TriForge — Milestone 5: Progression / Save Systems

**Project:** ${projectName}
**Prototype Goal:** ${scaffold.prototypeGoal}
**Survival Mode:** ${surv ? 'Yes' : 'No'}
**Inventory System:** ${inv ? 'Yes' : 'No'}
**Enemy/Combat Present:** ${enemy ? 'Yes' : 'No'}
**Generated:** ${generatedAt}
**Generated by:** TriForge pack.unreal-m5-execute (Phase 4, Step 6)
**Depends on:** M1 (Foundation), M2 (Primary Loop), M3 (Supporting Systems), M4 (Enemy / Combat)

${chainWarnings.length > 0 ? `---\n\n## Chain Integrity Warnings\n\n${chainWarnings.join('\n')}\n` : ''}
---

## Milestone Goal

${m6?.goal ?? 'Implement save-game persistence and a progression loop so the prototype remembers player state across sessions.'}

---

## Implementation Steps

${stepsMarkdown}

---

## Save Game Object (BP_SaveGame)

Create a Blueprint class named **BP_SaveGame** in \`Content/SaveData/\` with
**parent class: SaveGame** (search "Save Game" in the Blueprint picker).

See \`M5_SaveGameConfig.json\` for the full field spec.

### Required variables on BP_SaveGame

| Variable              | Type    | Default | Notes                                          |
|---------------------- |-------- |-------- |----------------------------------------------- |
| PlayerHealth          | Float   | 100.0   | Saved from BP_HealthComponent.CurrentHealth    |
${surv ? `| PlayerHunger          | Float   | 100.0   | Saved from BP_SurvivalStatsComponent           |
| PlayerThirst          | Float   | 100.0   | Saved from BP_SurvivalStatsComponent           |
` : ''}\
${inv ? `| InventoryItems        | Array   | []      | Serialized from BP_InventoryComponent          |
` : ''}\
${enemy ? `| TotalKills            | Integer | 0       | Incremented on enemy death                     |
| CurrentScore          | Integer | 0       | Updated per kill / objective                   |
` : ''}\
| LastCheckpointTag     | Name    | "Start" | FName tag of the last activated checkpoint     |
| TotalPlaytimeSec      | Float   | 0.0     | Accumulated play time in seconds               |

### Saving

\`\`\`
UGameplayStatics::SaveGameToSlot(BP_SaveGame_Instance, "Slot1", 0)
\`\`\`

Call this:
- When the player activates a checkpoint
- On intentional quit (from pause menu)
- Do NOT auto-save on every tick

### Loading

\`\`\`
Cast<BP_SaveGame>(UGameplayStatics::LoadGameFromSlot("Slot1", 0))
\`\`\`

Call this in **BP_GameMode BeginPlay**. If the slot does not exist, create a fresh
\`BP_SaveGame\` instance with defaults.

---

## Checkpoint System (BP_Checkpoint)

See \`M5_CheckpointConfig.json\` for placement and respawn parameters.

Create **BP_Checkpoint** (Actor Blueprint) in \`Content/Gameplay/\`:

1. Add a **Box Collision** component as the trigger volume.
2. On **ActorBeginOverlap** (PlayerCharacter only):
   - Set \`LastCheckpointTag\` on the active save game instance.
   - Call \`SaveGameToSlot\` to persist immediately.
   - Play a brief feedback effect (particle/sound).
3. On player death (from M2/M4 health system):
   - Load the save slot.
   - Teleport the player to the checkpoint actor tagged \`LastCheckpointTag\`.
   - Restore health/stats to saved values.

---

## Progression / XP (BP_ProgressionComponent)

See \`M5_ProgressionConfig.json\` for XP thresholds and unlock definitions.

Create **BP_ProgressionComponent** (Actor Component) in \`Content/Components/\`
and add it to **BP_PlayerCharacter**.

### How XP is awarded

${enemy ? `- On enemy death: add XP based on archetype threat level (see M4_EnemyArchetypes.json)\n` : ''}\
- On checkpoint activation: small XP bonus
${surv ? `- On resource collection: small XP bonus per rare resource\n` : ''}\

### Level-up flow

\`\`\`
AddXP(amount) → check if XP ≥ XPThresholds[CurrentLevel] → if yes, LevelUp()
LevelUp() → increment CurrentLevel, fire OnLevelUp delegate, check unlock table
\`\`\`

Fire **OnLevelUp** (Event Dispatcher) and bind it in WBP_HUD (M2) to show a
level-up notification overlay.

---

## Integration with Prior Milestones

| Milestone | Integration Point                                           |
|---------- |------------------------------------------------------------ |
| M2        | On death, restore health from save. OnLevelUp binds to HUD.|
| M3        | On load, restore inventory from \`InventoryItems\` save field.|
| M4        | On enemy death, award XP + increment kill count in save.   |

---

## Notes & Assumptions

- Use a single save slot ("Slot1") for the prototype — multi-slot save is a polish step.
- Do NOT save Blueprint object references — save plain data (float, int, string, name).
- Checkpoint tags must match exactly — use FName constants, not magic strings.
- If \`LoadGameFromSlot\` returns null, always fall back to fresh defaults (never crash).
- Progression unlocks in \`M5_ProgressionConfig.json\` are fully spec-defined — wire each to its Blueprint variable during implementation.

---

## Next Steps After M5

1. Create BP_SaveGame with all required variables.
2. Create BP_GameMode and implement save/load in BeginPlay and quit flow.
3. Create BP_Checkpoint and place at least one in the test level.
4. Create BP_ProgressionComponent and add to BP_PlayerCharacter.
${enemy ? '5. Wire enemy death → AddXP + TotalKills increment.\n' : ''}\
${!enemy ? '5' : '6'}. Verify save persists across Play-in-Editor sessions (stop and re-play).
${!enemy ? '6' : '7'}. Run \`pack.unreal-build\` to verify the full M1–M5 chain compiles cleanly.

---

*This file was generated by TriForge and can be safely edited.*
`;
}

function buildSaveGameConfigJson(
  projectName: string,
  scaffold: UnrealScaffoldResult,
  generatedAt: string,
): string {
  const surv  = isSurvivalGoal(scaffold);
  const inv   = hasInventoryItems(scaffold);
  const enemy = hasEnemyItems(scaffold);

  type SaveField = {
    id: string;
    type: string;
    defaultValue: unknown;
    sourceComponent: string;
    saveWhen: string;
    restoreOn: string;
    included: boolean;
    reason: string;
  };

  const fields: SaveField[] = [
    {
      id:               'PlayerHealth',
      type:             'Float',
      defaultValue:     100.0,
      sourceComponent:  'BP_HealthComponent.CurrentHealth',
      saveWhen:         'checkpoint activation',
      restoreOn:        'load game / respawn',
      included:         true,
      reason:           'Always — core prototype state.',
    },
    {
      id:               'PlayerHunger',
      type:             'Float',
      defaultValue:     100.0,
      sourceComponent:  'BP_SurvivalStatsComponent.CurrentHunger',
      saveWhen:         'checkpoint activation',
      restoreOn:        'load game / respawn',
      included:         surv,
      reason:           surv ? 'Survival prototype detected.' : 'Not included — no survival loop.',
    },
    {
      id:               'PlayerThirst',
      type:             'Float',
      defaultValue:     100.0,
      sourceComponent:  'BP_SurvivalStatsComponent.CurrentThirst',
      saveWhen:         'checkpoint activation',
      restoreOn:        'load game / respawn',
      included:         surv,
      reason:           surv ? 'Survival prototype detected.' : 'Not included — no survival loop.',
    },
    {
      id:               'InventoryItems',
      type:             'Array<S_ItemSaveData>',
      defaultValue:     [],
      sourceComponent:  'BP_InventoryComponent (serialize items to plain struct)',
      saveWhen:         'checkpoint activation',
      restoreOn:        'load game',
      included:         inv,
      reason:           inv ? 'Inventory scaffold detected.' : 'Not included — no inventory scaffold.',
    },
    {
      id:               'TotalKills',
      type:             'Integer',
      defaultValue:     0,
      sourceComponent:  'BP_ProgressionComponent.TotalKills',
      saveWhen:         'on enemy death',
      restoreOn:        'load game',
      included:         enemy,
      reason:           enemy ? 'Enemy/combat scaffold detected.' : 'Not included — no enemy loop.',
    },
    {
      id:               'CurrentScore',
      type:             'Integer',
      defaultValue:     0,
      sourceComponent:  'BP_ProgressionComponent.CurrentScore',
      saveWhen:         'on score change',
      restoreOn:        'load game',
      included:         enemy,
      reason:           enemy ? 'Enemy/combat scaffold detected.' : 'Not included — no scoring loop.',
    },
    {
      id:               'CurrentLevel',
      type:             'Integer',
      defaultValue:     1,
      sourceComponent:  'BP_ProgressionComponent.CurrentLevel',
      saveWhen:         'on level-up',
      restoreOn:        'load game',
      included:         true,
      reason:           'Always — progression level is core state.',
    },
    {
      id:               'CurrentXP',
      type:             'Integer',
      defaultValue:     0,
      sourceComponent:  'BP_ProgressionComponent.CurrentXP',
      saveWhen:         'on XP change',
      restoreOn:        'load game',
      included:         true,
      reason:           'Always — XP is core progression state.',
    },
    {
      id:               'LastCheckpointTag',
      type:             'Name',
      defaultValue:     'Start',
      sourceComponent:  'Set when checkpoint is activated',
      saveWhen:         'checkpoint activation',
      restoreOn:        'load game / respawn',
      included:         true,
      reason:           'Always — required for respawn placement.',
    },
    {
      id:               'TotalPlaytimeSec',
      type:             'Float',
      defaultValue:     0.0,
      sourceComponent:  'Accumulated in BP_GameMode tick',
      saveWhen:         'checkpoint activation + quit',
      restoreOn:        'load game',
      included:         true,
      reason:           'Always — useful for analytics and UI display.',
    },
  ];

  return JSON.stringify({
    triforgeVersion: '1.0',
    milestone:       'M5',
    project:         projectName,
    prototypeGoal:   scaffold.prototypeGoal,
    generatedAt,
    instructions: [
      'Create BP_SaveGame (SaveGame Blueprint) in Content/SaveData/.',
      'Add all included fields below as Blueprint variables.',
      'For inventory: create S_ItemSaveData struct with itemId (Name) + quantity (Integer).',
      'Use UGameplayStatics::SaveGameToSlot("Slot1", 0) on checkpoint activation.',
      'Use UGameplayStatics::LoadGameFromSlot("Slot1", 0) in BP_GameMode BeginPlay.',
      'If load returns null, create a fresh BP_SaveGame with default values.',
    ],
    saveGameBlueprint: {
      name:        'BP_SaveGame',
      parentClass: 'SaveGame',
      slotName:    'Slot1',
      userIndex:   0,
      contentPath: 'Content/SaveData/',
    },
    saveWhenEvents: [
      'Checkpoint activated (primary save trigger)',
      'Player quits via pause menu (secondary save trigger)',
    ],
    doNotSaveOn: [
      'Every tick (too frequent)',
      'Every enemy kill (use in-memory state, save on checkpoint)',
      'Application force-close (handle gracefully with BeginDestroy)',
    ],
    fields: fields.filter(f => f.included),
    excludedFields: fields.filter(f => !f.included).map(f => ({ id: f.id, reason: f.reason })),
  }, null, 2);
}

function buildProgressionConfigJson(
  projectName: string,
  scaffold: UnrealScaffoldResult,
  generatedAt: string,
): string {
  const enemy = hasEnemyItems(scaffold);
  const surv  = isSurvivalGoal(scaffold);
  const inv   = hasInventoryItems(scaffold);

  const xpThresholds = [0, 100, 250, 450, 700, 1000, 1400, 1900, 2500, 3200];

  return JSON.stringify({
    triforgeVersion: '1.0',
    milestone:       'M5',
    project:         projectName,
    prototypeGoal:   scaffold.prototypeGoal,
    generatedAt,
    instructions: [
      'Create BP_ProgressionComponent (Actor Component) in Content/Components/ and add to BP_PlayerCharacter.',
      'Add CurrentLevel (Integer, default 1), CurrentXP (Integer, default 0), TotalKills (Integer, default 0).',
      'Implement AddXP(amount): add to CurrentXP, check xpThresholds[CurrentLevel], call LevelUp() if met.',
      'Implement LevelUp(): increment CurrentLevel, fire OnLevelUp event dispatcher, check unlock table.',
      'Bind OnLevelUp in WBP_HUD (M2) to show a brief level-up notification.',
    ],
    componentBlueprint: {
      name:        'BP_ProgressionComponent',
      parentClass: 'ActorComponent',
      contentPath: 'Content/Components/',
    },
    maxLevel: xpThresholds.length,
    xpThresholds: xpThresholds.map((xp, i) => ({ level: i + 1, xpRequired: xp })),
    xpSources: [
      ...(enemy ? [
        { source: 'Kill: low-threat enemy',    xp: 15,  notes: 'Melee grunt / basic unit' },
        { source: 'Kill: medium-threat enemy', xp: 30,  notes: 'Ranged threat' },
        { source: 'Kill: high-threat enemy',   xp: 75,  notes: 'Heavy / tank archetype' },
      ] : []),
      { source: 'Checkpoint activated',        xp: 20,  notes: 'Reward for exploration progress' },
      ...(surv ? [
        { source: 'Rare resource collected',   xp: 10,  notes: 'From M3 item types' },
      ] : []),
      { source: 'Objective completed',         xp: 50,  notes: 'Stub — wire to specific objectives later' },
    ],
    unlocks: [
      {
        level:       2,
        id:          'unlock.increased_health',
        label:       'Increased Max Health',
        description: 'Player MaxHealth increases by 20.',
        effect:      'BP_HealthComponent.MaxHealth += 20',
        included:    true,
      },
      {
        level:       3,
        id:          'unlock.sprint_stamina',
        label:       'Improved Stamina',
        description: 'Player MaxStamina increases by 20.',
        effect:      'BP_SurvivalStatsComponent.MaxStamina += 20 (if M2 survival)',
        included:    true,
      },
      {
        level:       4,
        id:          'unlock.inventory_slot',
        label:       'Extra Inventory Slot',
        description: 'BP_InventoryComponent.MaxSlots increases by 2.',
        effect:      'BP_InventoryComponent.MaxSlots += 2',
        included:    inv,
      },
      {
        level:       5,
        id:          'unlock.damage_bonus',
        label:       'Combat Damage Bonus',
        description: 'Player melee damage increases by 5.',
        effect:      'Add +5 to player AttackDamage (M4 CombatConfig)',
        included:    enemy,
      },
    ].filter(u => u.included),
    balancingNotes: [
      'XP thresholds are starting values — tune after first playtest session.',
      'Goal: player should reach level 3 by the end of a 10-minute prototype run.',
      'Unlock effects are fully specified — wire each to its Blueprint variable using the effect field as the implementation target.',
    ],
  }, null, 2);
}

function buildCheckpointConfigJson(
  projectName: string,
  scaffold: UnrealScaffoldResult,
  generatedAt: string,
): string {
  const surv  = isSurvivalGoal(scaffold);

  return JSON.stringify({
    triforgeVersion: '1.0',
    milestone:       'M5',
    project:         projectName,
    prototypeGoal:   scaffold.prototypeGoal,
    generatedAt,
    instructions: [
      'Create BP_Checkpoint (Actor Blueprint) in Content/Gameplay/.',
      'Add a Box Collision component as the trigger volume (300x50x300 cm default).',
      'Add a Tag "Checkpoint" and a unique CheckpointTag (FName) editable variable per instance.',
      'On ActorBeginOverlap (PlayerCharacter only): set LastCheckpointTag on save instance, call SaveGameToSlot.',
      'On player death (wire from BP_HealthComponent.OnDeath): teleport player to checkpoint, restore health/stats.',
      'Place at least one BP_Checkpoint tagged "Start" at the player start location.',
    ],
    checkpointBlueprint: {
      name:          'BP_Checkpoint',
      parentClass:   'Actor',
      contentPath:   'Content/Gameplay/',
      triggerVolume: { widthCm: 300, heightCm: 300, depthCm: 50 },
    },
    defaultStartTag: 'Start',
    respawnBehavior: {
      teleportToCheckpoint: true,
      restoreHealth:        true,
      restoreStats:         surv,
      restoreInventory:     false,
      notes: surv
        ? 'Survival: restore health and survival stats on respawn. Inventory is NOT restored (permadeath-lite for items).'
        : 'Restore health only on respawn. Stats and inventory are not touched.',
    },
    feedbackOnActivation: [
      'Play a brief particle effect at the checkpoint location',
      'Play a short checkpoint sound cue',
      'Optionally show a "Progress Saved" HUD notification (bind to OnLevelUp-style overlay)',
    ],
    placementGuidance: [
      'Place one checkpoint near the start of each distinct area.',
      'Space checkpoints ~2–3 minutes of play apart in a prototype.',
      'Never place a checkpoint inside a hazard area or enemy spawn zone.',
      'Always tag each BP_Checkpoint instance with a unique CheckpointTag (e.g. "Zone1_Entry", "BossArena_Pre").',
    ],
    prototypeMinimum: {
      minimumCheckpoints: 2,
      required: ['Start', 'MidPoint'],
      notes: 'Prototype must have at least a Start checkpoint and one mid-game checkpoint to validate the save/load loop.',
    },
  }, null, 2);
}

// ── Main application function ─────────────────────────────────────────────────

/**
 * Apply Milestone 5 to the active Unreal project by generating structured
 * progression/save-system artifacts into <projectRoot>/TriForge/.
 */
export async function applyUnrealMilestone5(
  projectPath: string,
  projectName: string,
  scaffold: UnrealScaffoldResult,
  milestone: UnrealMilestoneResult,
  m1ManifestExists: boolean,
  m2ManifestExists: boolean,
  m3ManifestExists: boolean,
  m4ManifestExists: boolean,
): Promise<M5ApplicationResult> {
  const projectRoot = path.dirname(projectPath);
  const triforgeDir = path.join(projectRoot, 'TriForge');
  const generatedAt = new Date().toISOString();
  const appliedFiles: M5AppliedFile[] = [];
  const warnings: string[]            = [];
  const errors: string[]              = [];

  if (!m1ManifestExists) {
    warnings.push(
      'M1_Manifest.json not found — Milestone 1 (Foundation) may not be applied. ' +
      'Create BP_PlayerCharacter and BP_GameMode in Unreal Editor before wiring save/load (see M5_SaveGameConfig.json).',
    );
  }
  if (!m2ManifestExists) {
    warnings.push(
      'M2_Manifest.json not found — Milestone 2 (Primary Loop / HUD) may not be applied. ' +
      'Health restore on respawn and OnLevelUp HUD binding require M2 components.',
    );
  }
  if (!m3ManifestExists) {
    warnings.push(
      'M3_Manifest.json not found — Milestone 3 (Supporting Systems) may not be applied. ' +
      'Inventory save/restore field is included but has no source until M3 is wired.',
    );
  }
  if (!m4ManifestExists) {
    warnings.push(
      'M4_Manifest.json not found — Milestone 4 (Enemy / Combat) may not be applied. ' +
      'Kill count and score save fields are included but have no source until M4 is wired.',
    );
  }

  // ── Ensure TriForge directory exists ─────────────────────────────────────
  try {
    fs.mkdirSync(triforgeDir, { recursive: true });
  } catch (e: unknown) {
    const msg = e instanceof Error ? e.message : String(e);
    return {
      ok: false, projectRoot, triforgeDir,
      appliedFiles: [], warnings,
      errors: [`Failed to create TriForge directory at ${triforgeDir}: ${msg}`],
    };
  }

  // ── Write helper ──────────────────────────────────────────────────────────
  function writeFile(filename: string, content: string, description: string): boolean {
    const absolutePath = path.join(triforgeDir, filename);
    const relativePath = path.join('TriForge', filename);
    try {
      fs.writeFileSync(absolutePath, content, 'utf-8');
      appliedFiles.push({ absolutePath, relativePath, description });
      return true;
    } catch (e: unknown) {
      const msg = e instanceof Error ? e.message : String(e);
      warnings.push(`Could not write ${relativePath}: ${msg}`);
      return false;
    }
  }

  // ── Write M5 artifacts ────────────────────────────────────────────────────
  writeFile(
    'M5_Progression_Setup.md',
    buildSetupMarkdown(
      projectName, scaffold, milestone, generatedAt,
      m1ManifestExists, m2ManifestExists, m3ManifestExists, m4ManifestExists,
    ),
    'Milestone 5 implementation guide — save game, checkpoint system, progression/XP, and M1–M4 integration.',
  );

  writeFile(
    'M5_SaveGameConfig.json',
    buildSaveGameConfigJson(projectName, scaffold, generatedAt),
    'Save game spec — field list, source components, save/restore triggers (scaffold-adaptive).',
  );

  writeFile(
    'M5_ProgressionConfig.json',
    buildProgressionConfigJson(projectName, scaffold, generatedAt),
    'Progression/XP config — level thresholds, XP sources, and unlock specs (scaffold-adaptive).',
  );

  writeFile(
    'M5_CheckpointConfig.json',
    buildCheckpointConfigJson(projectName, scaffold, generatedAt),
    'Checkpoint config — trigger volume spec, respawn behavior, placement guidance, minimum requirements.',
  );

  // ── Manifest ──────────────────────────────────────────────────────────────
  const chainIntegrityNotes: string[] = [];
  if (!m1ManifestExists) chainIntegrityNotes.push('M1_Manifest.json missing.');
  if (!m2ManifestExists) chainIntegrityNotes.push('M2_Manifest.json missing — health restore on respawn requires M2.');
  if (!m3ManifestExists) chainIntegrityNotes.push('M3_Manifest.json missing — inventory restore requires M3.');
  if (!m4ManifestExists) chainIntegrityNotes.push('M4_Manifest.json missing — kill count / XP sources require M4.');

  const dependsOn: string[] = [];
  if (m4ManifestExists) dependsOn.push('M4_Manifest.json');
  else if (m3ManifestExists) dependsOn.push('M3_Manifest.json');
  else if (m2ManifestExists) dependsOn.push('M2_Manifest.json');
  else if (m1ManifestExists) dependsOn.push('M1_Manifest.json');

  const manifest = {
    triforgeVersion: '1.0',
    milestone:       'M5',
    project:         projectName,
    projectPath,
    generatedAt,
    packId:          'pack.unreal-m5-execute',
    dependsOn,
    files: appliedFiles.map(f => ({ relativePath: f.relativePath, description: f.description })),
    notes: [
      `Save fields: health always; survival stats ${isSurvivalGoal(scaffold) ? 'included' : 'excluded'}; inventory ${hasInventoryItems(scaffold) ? 'included' : 'excluded'}; kills/score ${hasEnemyItems(scaffold) ? 'included' : 'excluded'}`,
      'Save trigger: checkpoint activation (primary) + intentional quit (secondary)',
      'Progression: 10 levels; XP sources adapt to scaffold (kills, checkpoints, resources)',
      'Checkpoint: minimum 2 required for prototype (Start + MidPoint)',
      ...chainIntegrityNotes,
    ],
    recommendedNext: 'pack.unreal-editor-operate',
  };

  writeFile(
    'M5_Manifest.json',
    JSON.stringify(manifest, null, 2),
    'Machine-readable manifest of all M5 generated files for future pack chaining.',
  );

  // Companion Python script — run from Unreal Editor → Tools → Execute Python
  // Script to materialize the M5 save/progression scaffolds. Idempotent.
  writeFile(
    'M5_Apply.py',
    buildMilestone5PythonScript(projectName, scaffold, milestone, generatedAt),
    'Companion Python script — runs inside Unreal Editor to create the SaveGame, ' +
    'checkpoint, and progression component scaffolds described above.',
  );

  // ── B5: Post-write validation ──────────────────────────────────────────
  const validation = validateMilestoneBatch(
    appliedFiles.map(f => ({
      absolutePath:      f.absolutePath,
      relativePath:      f.relativePath,
      expectedMilestone: 'M5',
      isManifest:        f.relativePath.endsWith('M5_Manifest.json'),
    })),
  );
  if (validation.failed.length > 0) {
    warnings.push(...validation.warnings);
    const failedPaths = new Set(validation.failed.map(f => f.absolutePath));
    const survivingFiles = appliedFiles.filter(f => !failedPaths.has(f.absolutePath));
    appliedFiles.length = 0;
    appliedFiles.push(...survivingFiles);
  }

  const ok = appliedFiles.length > 0 && errors.length === 0;
  return { ok, projectRoot, triforgeDir, appliedFiles, warnings, errors };
}
