// ── vibeConsistencyChecker.ts — Audit product state against vibe profile ─────
//
// Checks whether a product's current state matches its intended vibe.
// Used by audit and rescue modes to identify where the product feels off.

import type {
  VibeProfile, VibeConsistencyResult, VibeConsistencyViolation,
  VibeDimension, VibeConfig,
} from './vibeTypes';
import { DEFAULT_VIBE_CONFIG, VIBE_DIMENSIONS } from './vibeTypes';

// ── Dimension keywords for current-state matching ───────────────────────────

const DIMENSION_KEYWORDS: Record<VibeDimension, string[]> = {
  layout:           ['layout', 'grid', 'structure', 'columns', 'rows', 'flow', 'arrangement'],
  typography:       ['font', 'type', 'text', 'heading', 'headline', 'serif', 'sans', 'weight'],
  spacing:          ['spacing', 'padding', 'margin', 'whitespace', 'gap', 'breathing room'],
  motion:           ['animation', 'transition', 'motion', 'scroll', 'hover', 'micro-interaction'],
  color:            ['color', 'palette', 'contrast', 'saturation', 'hue', 'dark', 'light', 'bright'],
  copy_tone:        ['tone', 'voice', 'copy', 'formal', 'casual', 'language', 'writing'],
  cta_style:        ['cta', 'button', 'call to action', 'action', 'click', 'submit'],
  trust_indicators: ['trust', 'badge', 'testimonial', 'review', 'guarantee', 'security', 'proof'],
  imagery:          ['image', 'photo', 'illustration', 'icon', 'visual', 'screenshot', 'graphic'],
  density:          ['density', 'dense', 'packed', 'sparse', 'minimal', 'crowded', 'clean'],
};

// ── Consistency checker ─────────────────────────────────────────────────────

export class VibeConsistencyChecker {
  private _config: VibeConfig;

  constructor(config?: Partial<VibeConfig>) {
    this._config = { ...DEFAULT_VIBE_CONFIG, ...config };
  }

  /**
   * Check consistency between intended vibe profile and current product state.
   *
   * The currentState parameter is a text description of the product's current
   * appearance, behavior, and feel — typically provided by the user or
   * generated by a council member analyzing the product.
   */
  check(profile: VibeProfile, currentState: string): VibeConsistencyResult {
    const lower = currentState.toLowerCase();
    const dimensionScores: Record<VibeDimension, number> = {} as any;
    const violations: VibeConsistencyViolation[] = [];
    const suggestions: string[] = [];

    for (const dim of VIBE_DIMENSIONS) {
      const score = this._scoreDimension(dim, profile.axes[dim], lower);
      dimensionScores[dim] = score;

      if (score < this._config.minConsistencyScore) {
        const violation = this._buildViolation(dim, profile.axes[dim], score);
        violations.push(violation);
        suggestions.push(this._buildSuggestion(dim, profile.axes[dim], score));
      }
    }

    const overallScore = Math.round(
      VIBE_DIMENSIONS.reduce((sum, dim) => sum + dimensionScores[dim], 0) / VIBE_DIMENSIONS.length,
    );

    return {
      profileId: profile.id,
      overallScore,
      dimensionScores,
      violations,
      suggestions,
    };
  }

  // ── Dimension scoring ─────────────────────────────────────────────────────

  /**
   * Score how well the current state matches the intended dimension value.
   *
   * Heuristic scoring:
   * - If the current state mentions dimension keywords, score higher
   * - If the intended value is extreme (>70 or <30), require stronger signals
   * - If dimension keywords are absent and intent is strong, score lower
   */
  private _scoreDimension(
    dimension: VibeDimension,
    intendedValue: number,
    currentStateLower: string,
  ): number {
    const keywords = DIMENSION_KEYWORDS[dimension];
    const mentionCount = keywords.filter(kw => currentStateLower.includes(kw)).length;
    const mentionRatio = mentionCount / keywords.length;

    // Neutral intent (40-60) is easy to satisfy
    if (intendedValue >= 40 && intendedValue <= 60) {
      return Math.round(70 + mentionRatio * 30);
    }

    // Strong intent (>70 or <30) requires evidence in the current state
    const intentStrength = Math.abs(intendedValue - 50) / 50; // 0-1

    if (mentionRatio >= 0.3) {
      // Keywords present — score based on how strong the signal is
      return Math.round(60 + mentionRatio * 40);
    }

    // Keywords absent, strong intent → likely mismatch
    return Math.round(80 - intentStrength * 50);
  }

  // ── Violation building ────────────────────────────────────────────────────

  private _buildViolation(
    dimension: VibeDimension,
    intendedValue: number,
    score: number,
  ): VibeConsistencyViolation {
    const direction = intendedValue > 60 ? 'high' : intendedValue < 40 ? 'low' : 'neutral';

    const severity: 'minor' | 'moderate' | 'critical' =
      score < 30 ? 'critical' :
      score < 50 ? 'moderate' :
      'minor';

    const directionLabel = direction === 'high' ? 'strong' : direction === 'low' ? 'minimal' : 'balanced';

    return {
      dimension,
      description: `Intended ${directionLabel} ${dimension.replace('_', ' ')} (${intendedValue}/100) but current state scores ${score}/100 — likely mismatch.`,
      severity,
    };
  }

  // ── Suggestion building ───────────────────────────────────────────────────

  private _buildSuggestion(
    dimension: VibeDimension,
    intendedValue: number,
    score: number,
  ): string {
    const gap = intendedValue - 50;
    const label = dimension.replace('_', ' ');

    if (gap > 20) {
      return `Increase ${label}: intended value is ${intendedValue}/100 but current implementation appears weaker. Review ${label}-related elements.`;
    }
    if (gap < -20) {
      return `Reduce ${label}: intended value is ${intendedValue}/100 but current implementation may be too prominent. Simplify ${label}-related elements.`;
    }
    return `Check ${label} consistency: score is ${score}/100, which may indicate a subtle mismatch in how ${label} is implemented.`;
  }
}
